# fix_vocab_dict.py

# 1. 기계번역 치명적 오역 및 문맥 오류 수동 교정 사전 (嬢 포함)
MANUAL_MEANING_FIXES = {
    # N1 레벨 교정
    "嬢": {"meaning": "young lady, unmarried woman", "meaningKo": "아가씨, 미혼 여성"},
    "唱える": {"meaning": "to advocate, to propose, to recite", "meaningKo": "주장하다, 제창하다, 외다"},
    "民宿": {"meaning": "guesthouse, bed and breakfast", "meaningKo": "민박, 게스트하우스"},
    "何気ない": {"meaning": "casual, unconcerned", "meaningKo": "무심한, 아무렇지 않은"},
    "勘弁": {"meaning": "pardon, forgiveness", "meaningKo": "용서, 봐줌"},
    "碁盤": {"meaning": "Go board", "meaningKo": "바둑판"},
    "召す": {"meaning": "to invite, to wear, to eat", "meaningKo": "부르시다, 입으시다, 잡수시다"},
    "給仕": {"meaning": "serving, waiting on a table", "meaningKo": "시중듦, 급사"},
    "宛てる": {"meaning": "to address (a letter to)", "meaningKo": "(편지 등을) ~앞으로 보내다"},
    "廃れる": {"meaning": "to become obsolete", "meaningKo": "쇠퇴하다, 유행이 지나다"},
    "辟易": {"meaning": "to be stumped, to be flabbergasted", "meaningKo": "질림, 진저리남"},
    "空き間": {"meaning": "vacant room, empty space", "meaningKo": "빈 방, 빈 공간"},
    "つり革": {"meaning": "strap (in a train/bus)", "meaningKo": "(전철·버스 등의) 손잡이"},
    "見晴らし": {"meaning": "view, prospect", "meaningKo": "전망, 경치"},
    "減点": {"meaning": "point deduction", "meaningKo": "감점"},
    "仕上がり": {"meaning": "finish, completion", "meaningKo": "완성, 마무리"},
    "腸": {"meaning": "intestines, guts", "meaningKo": "장, 창자"},
    "閉口": {"meaning": "being stumped, annoyed", "meaningKo": "질림, 말문이 막힘"},
    "放置": {"meaning": "leaving as is, neglect", "meaningKo": "방치"},
    "面目": {"meaning": "face, honor", "meaningKo": "체면, 면목"},
    "丸々": {"meaning": "completely, plump", "meaningKo": "통통하게, 완전히"},
    "人": {"meaning": "person", "meaningKo": "~인 (사람)"},
    "畜生": {"meaning": "damn it, beast", "meaningKo": "젠장, 짐승"},
    "お手上げ": {"meaning": "giving up, totally at a loss", "meaningKo": "속수무책, 두 손 두 발 다 듦"},
    "選考": {"meaning": "screening, selection", "meaningKo": "전형, 심사"},
    "単独": {"meaning": "independent, sole", "meaningKo": "단독"},
    "鮮やか": {"meaning": "vivid, clear", "meaningKo": "선명한, 산뜻한"},
    "下等": {"meaning": "inferior, low grade", "meaningKo": "하등, 저급한"},
    "不機嫌": {"meaning": "sullenness, bad mood", "meaningKo": "불쾌함, 언짢음"},
    "好き嫌い": {"meaning": "likes and dislikes", "meaningKo": "호불호, 편식"},
    "好悪": {"meaning": "likes and dislikes", "meaningKo": "호오, 좋고 싫음"},
    "木製": {"meaning": "wooden, made of wood", "meaningKo": "목제, 나무로 만든"},
    "金持ち": {"meaning": "rich person", "meaningKo": "부자, 재산가"},
    "怪しい": {"meaning": "suspicious, doubtful", "meaningKo": "수상한, 의심스러운"},
    "憎い": {"meaning": "hateful", "meaningKo": "미운, 얄미운"},
    "大空": {"meaning": "big sky, open sky", "meaningKo": "넓은 하늘, 대공"},
    "内乱": {"meaning": "civil war, rebellion", "meaningKo": "내란, 내전"},
    "布告": {"meaning": "decree, proclamation", "meaningKo": "포고, 선포"},
    "編": {"meaning": "compilation, volume", "meaningKo": "엮음, (책의) 편"},
    "云々": {"meaning": "and so on, etc.", "meaningKo": "운운, 이러쿵저러쿵"},
    "家来": {"meaning": "retainer, servant", "meaningKo": "가신, 부하"},
    "進呈": {"meaning": "presentation, giving", "meaningKo": "증정"},
    "西日": {"meaning": "setting sun", "meaningKo": "석양, 서쪽 햇빛"},
    "転任": {"meaning": "transfer", "meaningKo": "전임, 전근"},
    "領地": {"meaning": "territory, domain", "meaningKo": "영지, 영토"},
    "申し分": {"meaning": "shortcoming, defect", "meaningKo": "흠잡을 데, 불만족스러운 점"},
    "静的": {"meaning": "static", "meaningKo": "정적인"},
    "他意": {"meaning": "ulterior motive", "meaningKo": "딴마음, 다른 뜻"},
    "大柄": {"meaning": "large build, large pattern", "meaningKo": "큰 체격, 큼직한 무늬"},
    "転校": {"meaning": "transferring schools", "meaningKo": "전학"},
    "特派": {"meaning": "special dispatch", "meaningKo": "특파"},
    "反り": {"meaning": "warp, curvature", "meaningKo": "휨, 구부러짐"},
    "片言": {"meaning": "broken language, babble", "meaningKo": "서투른 말, 더듬거리는 말"},
    "利根": {"meaning": "intelligence, cleverness", "meaningKo": "영리함, 총명함"},
    "お供": {"meaning": "attendant, companion", "meaningKo": "수행원, 동반자"},
    "異見": {"meaning": "objection, different opinion", "meaningKo": "이견, 다른 의견"},
    "佳句": {"meaning": "beautiful phrase", "meaningKo": "가구, 훌륭한 글귀"},
    "画期": {"meaning": "epoch-making", "meaningKo": "획기적임, 새 시대를 엶"},
    "介抱": {"meaning": "nursing, looking after", "meaningKo": "간호, 간병"},
    "供する": {"meaning": "to offer, to serve", "meaningKo": "제공하다, 바치다"},
    "恐れ入る": {"meaning": "to be obliged, to be sorry", "meaningKo": "황송하다, 죄송하다"},
    "凝らす": {"meaning": "to concentrate, to devote", "meaningKo": "마음을 집중시키다, 응결시키다"},
    "凝る": {"meaning": "to become stiff, to be absorbed in", "meaningKo": "뻐근하다, 열중하다, 응고하다"},
    "言伝": {"meaning": "message, word", "meaningKo": "전언, 전갈"},
    "溝": {"meaning": "ditch, gutter, gulf", "meaningKo": "도랑, 홈, 격차"},
    "合わせ": {"meaning": "joint, match", "meaningKo": "맞춤, 겹침"},
    "氏": {"meaning": "Mr., family", "meaningKo": "씨, 가문"},
    "賜る": {"meaning": "to be given, to be granted", "meaningKo": "내려주시다, 받다"},
    "社": {"meaning": "shrine", "meaningKo": "신사(사당)"},
    "手回し": {"meaning": "preparations, turning by hand", "meaningKo": "사전 준비, 손으로 돌림"},
    "重": {"meaning": "layer, -fold", "meaningKo": "겹, 층"},
    "出切る": {"meaning": "to be completely out, to exhaust", "meaningKo": "전부 나오다, 다 떨어지다"},
    "世辞": {"meaning": "flattery, compliment", "meaningKo": "겉치레말, 인사말"},
    "生真面目": {"meaning": "overly serious, earnest", "meaningKo": "고지식함, 아주 성실함"},
    "駄作": {"meaning": "poor piece of work", "meaningKo": "졸작"},
    "退ける": {"meaning": "to repel, to reject", "meaningKo": "물리치다, 물러나게 하다"},
    "代": {"meaning": "price, charge, era", "meaningKo": "대금, 시대"},
    "中っ腹": {"meaning": "anger", "meaningKo": "부아가 남, 화남"},
    "沈澱": {"meaning": "precipitation, sedimentation", "meaningKo": "침전 (액체가 가라앉음)"},
    "殿": {"meaning": "rear, rearguard", "meaningKo": "(군대의) 후미, 맨 뒤"},
    "当て字": {"meaning": "phonetic equivalent", "meaningKo": "아테지 (뜻에 관계없이 음을 빌려 쓰는 한자)"},
    "反": {"meaning": "roll of cloth, anti-", "meaningKo": "(옷감의) 한 필, 반대"},
    "偏": {"meaning": "left-hand radical, bias", "meaningKo": "(한자의) 변, 치우침"},
    "呆然": {"meaning": "dumbfounded, stunned", "meaningKo": "아연함, 어이가 없어 멍함"},
    "末": {"meaning": "end, tip, future", "meaningKo": "끝, 장래"},
    "目論見": {"meaning": "plan, scheme, intention", "meaningKo": "계획, 의도, 목적"},
    "溜まり": {"meaning": "gathering, puddle", "meaningKo": "고임, 웅덩이"},
    "し尿": {"meaning": "human waste, excreta", "meaningKo": "분뇨"},
    "洒落": {"meaning": "stylish, joke", "meaningKo": "멋부림, 세련됨, 농담"},
    "上手": {"meaning": "upper part, superiority, better", "meaningKo": "위쪽, (바둑 등에서) 윗수"},
    "等": {"meaning": "class, grade, etc.", "meaningKo": "등급, 등"},
    "虚ろ": {"meaning": "hollow, blank", "meaningKo": "공허함, 텅 빔"},
    "丁々": {"meaning": "clashing continuously", "meaningKo": "쩡쩡 (무기 부딪치는 소리), 격렬한 모양"},
    "捕吏": {"meaning": "constable, police", "meaningKo": "포리, 포졸"},
    "一見": {"meaning": "unintroduced first-time customer", "meaningKo": "단골이 아닌 첫 손님, 첫 대면"},
    "豪儀": {"meaning": "great, grand", "meaningKo": "훌륭함, 굉장함"},
    "魂": {"meaning": "soul, spirit", "meaningKo": "영혼, 혼"},
    "頃": {"meaning": "time, about", "meaningKo": "~무렵, 시기"},
    "甲": {"meaning": "carapace, shell, instep", "meaningKo": "갑, (거북이 등의) 등딱지, 발등"},
    "地方": {"meaning": "region, rural area", "meaningKo": "지방, 시골"},
    "見渡す": {"meaning": "to look out over, to survey", "meaningKo": "멀리 바라보다"},
    "固体": {"meaning": "solid (state)", "meaningKo": "고체"},
    "光熱費": {"meaning": "heating and electricity expenses", "meaningKo": "광열비"},
    "購買": {"meaning": "purchasing", "meaningKo": "구매"},
    "降伏": {"meaning": "surrender", "meaningKo": "항복"},
    "使い道": {"meaning": "use, purpose", "meaningKo": "쓸모, 용도"},
    "始発": {"meaning": "first train/bus", "meaningKo": "시발, 첫차"},
    "治まる": {"meaning": "to be governed, to die down", "meaningKo": "다스려지다, 가라앉다"},
    "取り次ぐ": {"meaning": "to act as an agent, to convey", "meaningKo": "전하다, 중개하다"},
    "手遅れ": {"meaning": "being too late", "meaningKo": "때를 놓침, 늦음"},
    "出題": {"meaning": "setting a question", "meaningKo": "출제"},
    "諸君": {"meaning": "gentlemen, you", "meaningKo": "제군, 여러분"},
    "徐行": {"meaning": "driving slowly", "meaningKo": "서행"},
    "象": {"meaning": "shape, image, elephant", "meaningKo": "형상, 코끼리"},
    "情け": {"meaning": "sympathy, compassion", "meaningKo": "인정, 동정"},
    "心中": {"meaning": "lovers' suicide, innermost thoughts", "meaningKo": "동반 자살, 속마음"},
    "尽きる": {"meaning": "to be exhausted, to run out", "meaningKo": "다하다, 바닥나다"},
    "据える": {"meaning": "to place, to set", "meaningKo": "설치하다, 앉히다"},
    "裾": {"meaning": "hem, skirt (of a mountain)", "meaningKo": "옷자락, 산자락"},
    "整列": {"meaning": "lining up", "meaningKo": "정렬"},
    "晴天": {"meaning": "clear weather", "meaningKo": "청천, 맑은 하늘"},
    "盛り上がる": {"meaning": "to get excited, to swell", "meaningKo": "분위기가 달아오르다, 솟아오르다"},
    "折衷": {"meaning": "compromise, blending", "meaningKo": "절충"},
    "前置き": {"meaning": "introduction, preamble", "meaningKo": "서론, 머리말"},
    "相対": {"meaning": "facing each other, relative", "meaningKo": "상대, 마주 봄"},
    "体裁": {"meaning": "appearance, format", "meaningKo": "체면, 겉모양, 체재"},
    "退治": {"meaning": "extermination", "meaningKo": "퇴치"},
    "定食": {"meaning": "set meal", "meaningKo": "정식, 백반"},
    "道場": {"meaning": "dojo, training hall", "meaningKo": "도장(무술 수련장)"},
    "鈍感": {"meaning": "insensitive, dull", "meaningKo": "둔감함"},
    "年輪": {"meaning": "annual ring", "meaningKo": "나이테"},
    "拝啓": {"meaning": "Dear Sir/Madam", "meaningKo": "삼가 아룁니다 (편지 서두)"},
    "発作": {"meaning": "fit, spasm", "meaningKo": "발작"},
    "薄弱": {"meaning": "weak, feeble", "meaningKo": "박약함"},
    "半端": {"meaning": "half-hearted, incomplete", "meaningKo": "어중간함, 짝이 안 맞음"},
    "非行": {"meaning": "delinquency, misconduct", "meaningKo": "비행, 나쁜 행동"},
    "不当": {"meaning": "unfair, unjust", "meaningKo": "부당함"},
    "本音": {"meaning": "true feelings", "meaningKo": "본심, 속마음"},
    "連日": {"meaning": "every day", "meaningKo": "연일"},
    "早急": {"meaning": "urgent", "meaningKo": "조급함, 몹시 급함"},
    "一括": {"meaning": "all together", "meaningKo": "일괄"},
    "園": {"meaning": "garden", "meaningKo": "동산, 원"},
    "何と": {"meaning": "what, how", "meaningKo": "무려, 얼마나"},
    "及ぶ": {"meaning": "to reach, to amount to", "meaningKo": "미치다, 달하다"},
    "固める": {"meaning": "to harden, to solidify", "meaningKo": "굳히다, 확고히 하다"},
    "作用": {"meaning": "action, effect", "meaningKo": "작용"},
    "自覚": {"meaning": "self-awareness", "meaningKo": "자각"},
    "丈": {"meaning": "length, measure", "meaningKo": "기장, 길이"},
    "前例": {"meaning": "precedent", "meaningKo": "전례"},
    "肉親": {"meaning": "blood relative", "meaningKo": "혈육, 육친"},
    "赴任": {"meaning": "taking up a new post", "meaningKo": "부임"},
    "様式": {"meaning": "style, form", "meaningKo": "양식, 형식"},
    "恋愛": {"meaning": "romantic love", "meaningKo": "연애"},
    "言論": {"meaning": "speech, expression", "meaningKo": "언론"},
    "行": {"meaning": "line, row", "meaningKo": "(글의) 행, 줄"},
    "至って": {"meaning": "very, exceedingly", "meaningKo": "지극히, 매우"},
    "情熱": {"meaning": "passion", "meaningKo": "정열"},
    "日の丸": {"meaning": "the Japanese flag", "meaningKo": "일장기"},
    "日ごろ": {"meaning": "normally, always", "meaningKo": "평소, 늘"},
    "有機": {"meaning": "organic", "meaningKo": "유기적인, 유기농의"},
    "用品": {"meaning": "supplies, articles", "meaningKo": "용품"},
    "本文": {"meaning": "text, body", "meaningKo": "본문"},
    "解剖": {"meaning": "dissection, anatomy", "meaningKo": "해부"},
    "弓": {"meaning": "bow", "meaningKo": "활"},
    "受身": {"meaning": "passive, receiving", "meaningKo": "수동태, 수세"},
    "出世": {"meaning": "success in life, promotion", "meaningKo": "출세"},
    "役職": {"meaning": "executive position, post", "meaningKo": "직책"},
    "唱える": {"meaning": "to advocate, to propose, to recite", "meaningKo": "주장하다, 제창하다, 외다"},
    "民宿": {"meaning": "guesthouse, bed and breakfast", "meaningKo": "민박, 게스트하우스"},
    "何気ない": {"meaning": "casual, unconcerned", "meaningKo": "무심한, 아무렇지 않은"},
    "勘弁": {"meaning": "pardon, forgiveness", "meaningKo": "용서, 봐줌"},
    "碁盤": {"meaning": "Go board", "meaningKo": "바둑판"},
    "召す": {"meaning": "to invite, to wear, to eat", "meaningKo": "부르시다, 입으시다, 잡수시다"},
    "給仕": {"meaning": "serving, waiting on a table", "meaningKo": "시중듦, 급사"},
    "宛てる": {"meaning": "to address (a letter to)", "meaningKo": "(편지 등을) ~앞으로 보내다"},
    "廃れる": {"meaning": "to become obsolete", "meaningKo": "쇠퇴하다, 유행이 지나다"},
    "辟易": {"meaning": "to be stumped, to be flabbergasted", "meaningKo": "질림, 진저리남"},
    "空き間": {"meaning": "vacant room, empty space", "meaningKo": "빈 방, 빈 공간"},
    "つり革": {"meaning": "strap (in a train/bus)", "meaningKo": "(전철·버스 등의) 손잡이"},
    "見晴らし": {"meaning": "view, prospect", "meaningKo": "전망, 경치"},
    "減点": {"meaning": "point deduction", "meaningKo": "감점"},
    "仕上がり": {"meaning": "finish, completion", "meaningKo": "완성, 마무리"},
    "腸": {"meaning": "intestines, guts", "meaningKo": "장, 창자"},
    "閉口": {"meaning": "being stumped, annoyed", "meaningKo": "질림, 말문이 막힘"},
    "放置": {"meaning": "leaving as is, neglect", "meaningKo": "방치"},
    "面目": {"meaning": "face, honor", "meaningKo": "체면, 면목"},
    "丸々": {"meaning": "completely, plump", "meaningKo": "통통하게, 완전히"},
    "人": {"meaning": "person", "meaningKo": "~인 (사람)"},
    "畜生": {"meaning": "damn it, beast", "meaningKo": "젠장, 짐승"},
    "お手上げ": {"meaning": "giving up, totally at a loss", "meaningKo": "속수무책, 두 손 두 발 다 듦"},
    "選考": {"meaning": "screening, selection", "meaningKo": "전형, 심사"},
    "単独": {"meaning": "independent, sole", "meaningKo": "단독"},
    "鮮やか": {"meaning": "vivid, clear", "meaningKo": "선명한, 산뜻한"},
    "下等": {"meaning": "inferior, low grade", "meaningKo": "하등, 저급한"},
    "不機嫌": {"meaning": "sullenness, bad mood", "meaningKo": "불쾌함, 언짢음"},
    "好き嫌い": {"meaning": "likes and dislikes", "meaningKo": "호불호, 편식"},
    "好悪": {"meaning": "likes and dislikes", "meaningKo": "호오, 좋고 싫음"},
    "木製": {"meaning": "wooden, made of wood", "meaningKo": "목제, 나무로 만든"},
    "金持ち": {"meaning": "rich person", "meaningKo": "부자, 재산가"},
    "お産": {"meaning": "childbirth, delivery", "meaningKo": "출산, 분만"},
    "怪しい": {"meaning": "suspicious, doubtful", "meaningKo": "수상한, 의심스러운"},
    "憎い": {"meaning": "hateful", "meaningKo": "미운, 얄미운"},
    "大空": {"meaning": "big sky, open sky", "meaningKo": "넓은 하늘, 대공"},
    "内乱": {"meaning": "civil war, rebellion", "meaningKo": "내란, 내전"},
    "布告": {"meaning": "decree, proclamation", "meaningKo": "포고, 선포"},
    "編": {"meaning": "compilation, volume", "meaningKo": "엮음, (책의) 편"},
    "云々": {"meaning": "and so on, etc.", "meaningKo": "운운, 이러쿵저러쿵"},
    "家来": {"meaning": "retainer, servant", "meaningKo": "가신, 부하"},
    "進呈": {"meaning": "presentation, giving", "meaningKo": "증정"},
    "西日": {"meaning": "setting sun", "meaningKo": "석양, 서쪽 햇빛"},
    "転任": {"meaning": "transfer", "meaningKo": "전임, 전근"},
    "領地": {"meaning": "territory, domain", "meaningKo": "영지, 영토"},
    "申し分": {"meaning": "shortcoming, defect", "meaningKo": "흠잡을 데, 불만족스러운 점"},
    "静的": {"meaning": "static", "meaningKo": "정적인"},
    "他意": {"meaning": "ulterior motive", "meaningKo": "딴마음, 다른 뜻"},
    "大柄": {"meaning": "large build, large pattern", "meaningKo": "큰 체격, 큼직한 무늬"},
    "転校": {"meaning": "transferring schools", "meaningKo": "전학"},
    "特派": {"meaning": "special dispatch", "meaningKo": "특파"},
    "反り": {"meaning": "warp, curvature", "meaningKo": "휨, 구부러짐"},
    "片言": {"meaning": "broken language, babble", "meaningKo": "서투른 말, 더듬거리는 말"},
    "利根": {"meaning": "intelligence, cleverness", "meaningKo": "영리함, 총명함"},
    "お供": {"meaning": "attendant, companion", "meaningKo": "수행원, 동반자"},
    "異見": {"meaning": "objection, different opinion", "meaningKo": "이견, 다른 의견"},
    "佳句": {"meaning": "beautiful phrase", "meaningKo": "가구, 훌륭한 글귀"},
    "画期": {"meaning": "epoch-making", "meaningKo": "획기적임, 새 시대를 엶"},
    "介抱": {"meaning": "nursing, looking after", "meaningKo": "간호, 간병"},
    "供する": {"meaning": "to offer, to serve", "meaningKo": "제공하다, 바치다"},
    "恐れ入る": {"meaning": "to be obliged, to be sorry", "meaningKo": "황송하다, 죄송하다"},
    "凝らす": {"meaning": "to concentrate, to devote", "meaningKo": "마음을 집중시키다, 응결시키다"},
    "凝る": {"meaning": "to become stiff, to be absorbed in", "meaningKo": "뻐근하다, 열중하다, 응고하다"},
    "言伝": {"meaning": "message, word", "meaningKo": "전언, 전갈"},
    "溝": {"meaning": "ditch, gutter, gulf", "meaningKo": "도랑, 홈, 격차"},
    "合わせ": {"meaning": "joint, match", "meaningKo": "맞춤, 겹침"},
    "氏": {"meaning": "Mr., family", "meaningKo": "씨, 가문"},
    "賜る": {"meaning": "to be given, to be granted", "meaningKo": "내려주시다, 받다"},
    "社": {"meaning": "shrine", "meaningKo": "신사(사당)"},
    "手回し": {"meaning": "preparations, turning by hand", "meaningKo": "사전 준비, 손으로 돌림"},
    "重": {"meaning": "layer, -fold", "meaningKo": "겹, 층"},
    "出切る": {"meaning": "to be completely out, to exhaust", "meaningKo": "전부 나오다, 다 떨어지다"},
    "世辞": {"meaning": "flattery, compliment", "meaningKo": "겉치레말, 인사말"},
    "生真面目": {"meaning": "overly serious, earnest", "meaningKo": "고지식함, 아주 성실함"},
    "駄作": {"meaning": "poor piece of work", "meaningKo": "졸작"},
    "退ける": {"meaning": "to repel, to reject", "meaningKo": "물리치다, 물러나게 하다"},
    "代": {"meaning": "price, charge, era", "meaningKo": "대금, 시대"},
    "中っ腹": {"meaning": "anger", "meaningKo": "부아가 남, 화남"},
    "沈澱": {"meaning": "precipitation, sedimentation", "meaningKo": "침전 (액체가 가라앉음)"},
    "殿": {"meaning": "rear, rearguard", "meaningKo": "(군대의) 후미, 맨 뒤"},
    "当て字": {"meaning": "phonetic equivalent", "meaningKo": "아테지 (뜻에 관계없이 음을 빌려 쓰는 한자)"},
    "反": {"meaning": "roll of cloth, anti-", "meaningKo": "(옷감의) 한 필, 반대"},
    "偏": {"meaning": "left-hand radical, bias", "meaningKo": "(한자의) 변, 치우침"},
    "呆然": {"meaning": "dumbfounded, stunned", "meaningKo": "아연함, 어이가 없어 멍함"},
    "末": {"meaning": "end, tip, future", "meaningKo": "끝, 장래"},
    "目論見": {"meaning": "plan, scheme, intention", "meaningKo": "계획, 의도, 목적"},
    "溜まり": {"meaning": "gathering, puddle", "meaningKo": "고임, 웅덩이"},
    "し尿": {"meaning": "human waste, excreta", "meaningKo": "분뇨"},
    "洒落": {"meaning": "stylish, joke", "meaningKo": "멋부림, 세련됨, 농담"},
    "上手": {"meaning": "upper part, superiority, better", "meaningKo": "위쪽, (바둑 등에서) 윗수"},
    "等": {"meaning": "class, grade, etc.", "meaningKo": "등급, 등"},
    "虚ろ": {"meaning": "hollow, blank", "meaningKo": "공허함, 텅 빔"},
    "丁々": {"meaning": "clashing continuously", "meaningKo": "쩡쩡 (무기 부딪치는 소리), 격렬한 모양"},
    "捕吏": {"meaning": "constable, police", "meaningKo": "포리, 포졸"},
    "一見": {"meaning": "unintroduced first-time customer", "meaningKo": "단골이 아닌 첫 손님, 첫 대면"},
    "豪儀": {"meaning": "great, grand", "meaningKo": "훌륭함, 굉장함"},
    "魂": {"meaning": "soul, spirit", "meaningKo": "영혼, 혼"},
    "頃": {"meaning": "time, about", "meaningKo": "~무렵, 시기"},
    "甲": {"meaning": "carapace, shell, instep", "meaningKo": "갑, (거북이 등의) 등딱지, 발등"},
    "地方": {"meaning": "region, rural area, accompanist", "meaningKo": "지방, 시골, (음악) 반주자"},
    "見渡す": {"meaning": "to look out over, to survey", "meaningKo": "멀리 바라보다"},
    "固体": {"meaning": "solid (state)", "meaningKo": "고체"},
    "光熱費": {"meaning": "heating and electricity expenses", "meaningKo": "광열비"},
    "購買": {"meaning": "purchasing", "meaningKo": "구매"},
    "降伏": {"meaning": "surrender", "meaningKo": "항복"},
    "使い道": {"meaning": "use, purpose", "meaningKo": "쓸모, 용도"},
    "始発": {"meaning": "first train/bus", "meaningKo": "시발, 첫차"},
    "治まる": {"meaning": "to be governed, to die down", "meaningKo": "다스려지다, 가라앉다"},
    "取り次ぐ": {"meaning": "to act as an agent, to convey", "meaningKo": "전하다, 중개하다"},
    "手遅れ": {"meaning": "being too late", "meaningKo": "때를 놓침, 늦음"},
    "出題": {"meaning": "setting a question", "meaningKo": "출제"},
    "諸君": {"meaning": "gentlemen, you", "meaningKo": "제군, 여러분"},
    "徐行": {"meaning": "driving slowly", "meaningKo": "서행"},
    "象": {"meaning": "shape, image, elephant", "meaningKo": "형상, 코끼리"},
    "情け": {"meaning": "sympathy, compassion", "meaningKo": "인정, 동정"},
    "心中": {"meaning": "lovers' suicide, innermost thoughts", "meaningKo": "동반 자살, 속마음"},
    "尽きる": {"meaning": "to be exhausted, to run out", "meaningKo": "다하다, 바닥나다"},
    "据える": {"meaning": "to place, to set", "meaningKo": "설치하다, 앉히다"},
    "裾": {"meaning": "hem, skirt (of a mountain)", "meaningKo": "옷자락, 산자락"},
    "整列": {"meaning": "lining up", "meaningKo": "정렬"},
    "晴天": {"meaning": "clear weather", "meaningKo": "청천, 맑은 하늘"},
    "盛り上がる": {"meaning": "to get excited, to swell", "meaningKo": "분위기가 달아오르다, 솟아오르다"},
    "折衷": {"meaning": "compromise, blending", "meaningKo": "절충"},
    "前置き": {"meaning": "introduction, preamble", "meaningKo": "서론, 머리말"},
    "相対": {"meaning": "facing each other, relative", "meaningKo": "상대, 마주 봄"},
    "体裁": {"meaning": "appearance, format", "meaningKo": "체면, 겉모양, 체재"},
    "退治": {"meaning": "extermination", "meaningKo": "퇴치"},
    "定食": {"meaning": "set meal", "meaningKo": "정식, 백반"},
    "道場": {"meaning": "dojo, training hall", "meaningKo": "도장(무술 수련장)"},
    "鈍感": {"meaning": "insensitive, dull", "meaningKo": "둔감함"},
    "年輪": {"meaning": "annual ring", "meaningKo": "나이테"},
    "拝啓": {"meaning": "Dear Sir/Madam", "meaningKo": "삼가 아룁니다 (편지 서두)"},
    "発作": {"meaning": "fit, spasm", "meaningKo": "발작"},
    "薄弱": {"meaning": "weak, feeble", "meaningKo": "박약함"},
    "半端": {"meaning": "half-hearted, incomplete", "meaningKo": "어중간함, 짝이 안 맞음"},
    "非行": {"meaning": "delinquency, misconduct", "meaningKo": "비행, 나쁜 행동"},
    "不当": {"meaning": "unfair, unjust", "meaningKo": "부당함"},
    "本音": {"meaning": "true feelings", "meaningKo": "본심, 속마음"},
    "連日": {"meaning": "every day", "meaningKo": "연일"},
    "早急": {"meaning": "urgent", "meaningKo": "조급함, 몹시 급함"},
    "一括": {"meaning": "all together", "meaningKo": "일괄"},
    "園": {"meaning": "garden", "meaningKo": "동산, 원"},
    "何と": {"meaning": "what, how", "meaningKo": "무려, 얼마나"},
    "及ぶ": {"meaning": "to reach, to amount to", "meaningKo": "미치다, 달하다"},
    "固める": {"meaning": "to harden, to solidify", "meaningKo": "굳히다, 확고히 하다"},
    "作用": {"meaning": "action, effect", "meaningKo": "작용"},
    "自覚": {"meaning": "self-awareness", "meaningKo": "자각"},
    "丈": {"meaning": "length, measure", "meaningKo": "기장, 길이"},
    "前例": {"meaning": "precedent", "meaningKo": "전례"},
    "肉親": {"meaning": "blood relative", "meaningKo": "혈육, 육친"},
    "赴任": {"meaning": "taking up a new post", "meaningKo": "부임"},
    "様式": {"meaning": "style, form", "meaningKo": "양식, 형식"},
    "恋愛": {"meaning": "romantic love", "meaningKo": "연애"},
    "言論": {"meaning": "speech, expression", "meaningKo": "언론"},
    "行": {"meaning": "line, row", "meaningKo": "(글의) 행, 줄"},
    "至って": {"meaning": "very, exceedingly", "meaningKo": "지극히, 매우"},
    "情熱": {"meaning": "passion", "meaningKo": "정열"},
    "日の丸": {"meaning": "the Japanese flag", "meaningKo": "일장기"},
    "日ごろ": {"meaning": "normally, always", "meaningKo": "평소, 늘"},
    "有機": {"meaning": "organic", "meaningKo": "유기적인, 유기농의"},
    "用品": {"meaning": "supplies, articles", "meaningKo": "용품"},
    "本文": {"meaning": "text, body", "meaningKo": "본문"},
    "解剖": {"meaning": "dissection, anatomy", "meaningKo": "해부"},
    "弓": {"meaning": "bow", "meaningKo": "활"},
    "受身": {"meaning": "passive, receiving", "meaningKo": "수동태, 수세"},
    "出世": {"meaning": "success in life, promotion", "meaningKo": "출세"},
    "役職": {"meaning": "executive position, post", "meaningKo": "직책"},

    # From N2:
    "あっさり": {"meaning": "easily, flatly", "meaningKo": "깨끗하게, 산뜻하게, 쉽게"},
    "あっという間": {"meaning": "a blink of time", "meaningKo": "눈 깜짝할 사이"},
    "いざ": {"meaning": "now, come", "meaningKo": "자 (권유, 결심)"},
    "おおい": {"meaning": "hey!", "meaningKo": "어이!"},
    "お似合い": {"meaning": "well-matched", "meaningKo": "잘 어울림"},
    "がる": {"meaning": "to show signs of being", "meaningKo": "~해 하다 (감정을 나타냄)"},
    "ぐっと": {"meaning": "suddenly, with a jerk", "meaningKo": "힘을 주어 단숨에 하는 모양, 훨씬"},
    "この度": {"meaning": "this occasion", "meaningKo": "이번, 이 번에"},
    "すんなり": {"meaning": "slim, smoothly", "meaningKo": "매끄럽게, 수월하게, 늘씬하게"},
    "だらし無い": {"meaning": "slovenly", "meaningKo": "단정치 못하다, 야무지지 못하다"},
    "どうやら": {"meaning": "possibly, apparently", "meaningKo": "아무래도, 어쩐지"},
    "ひと昔": {"meaning": "ages", "meaningKo": "옛날, 십 년 전"},
    "ひょっと": {"meaning": "possibly", "meaningKo": "만약, 어쩌면"},
    "ほっと": {"meaning": "with a feeling of relief", "meaningKo": "안도하는 모양, 한숨 돌리는 모양"},
    "やむを得ない": {"meaning": "cannot be helped", "meaningKo": "어쩔 수 없다, 부득이하다"},
    "やり甲斐": {"meaning": "being worth doing", "meaningKo": "보람"},
    "よそ見": {"meaning": "looking away", "meaningKo": "한눈팔기"},
    "一刻": {"meaning": "minute, moment", "meaningKo": "일각, 한시"},
    "一助": {"meaning": "help", "meaningKo": "일조, 약간의 도움"},
    "一向に": {"meaning": "completely", "meaningKo": "전혀, 조금도"},
    "一変": {"meaning": "complete change", "meaningKo": "일변, 완전히 변함"},
    "一括": {"meaning": "lumping together", "meaningKo": "일괄"},
    "一斉に": {"meaning": "simultaneously", "meaningKo": "일제히"},
    "一旦": {"meaning": "once", "meaningKo": "일단, 한 번"},
    "一段": {"meaning": "more", "meaningKo": "한층 더, 한 단"},
    "一段落": {"meaning": "reaching a stopping place", "meaningKo": "일단락"},
    "一気に": {"meaning": "in one go", "meaningKo": "단숨에"},
    "一色": {"meaning": "same tendency", "meaningKo": "일색, 한 가지 색"},
    "一覧": {"meaning": "look", "meaningKo": "일람, 한눈에 봄"},
    "一転": {"meaning": "complete change", "meaningKo": "일전, 완전히 바뀜"},
    "下書き": {"meaning": "draft", "meaningKo": "초안, 밑그림"},
    "下記": {"meaning": "the following", "meaningKo": "하기, 아래에 적음"},
    "不採用": {"meaning": "rejection", "meaningKo": "불채용"},
    "不明瞭": {"meaning": "dimness", "meaningKo": "불명료함"},
    "両端": {"meaning": "both ends", "meaningKo": "양쪽 끝"},
    "主力": {"meaning": "main force", "meaningKo": "주력"},
    "乗り継ぐ": {"meaning": "to connect", "meaningKo": "갈아타다"},
    "乗り越える": {"meaning": "to climb over", "meaningKo": "뛰어넘다, 극복하다"},
    "乗車": {"meaning": "boarding", "meaningKo": "승차"},
    "乱暴": {"meaning": "violence", "meaningKo": "난폭함"},
    "予め": {"meaning": "beforehand", "meaningKo": "미리, 사전에"},
    "事例": {"meaning": "example", "meaningKo": "사례"},
    "事典": {"meaning": "encyclopedia", "meaningKo": "사전 (백과사전)"},
    "事物": {"meaning": "things", "meaningKo": "사물"},
    "人前": {"meaning": "presence of other people", "meaningKo": "남의 앞"},
    "仕草": {"meaning": "gesture", "meaningKo": "행동, 태도, 몸짓"},
    "付け加え": {"meaning": "addition", "meaningKo": "추가, 덧붙임"},
    "付近": {"meaning": "neighbourhood", "meaningKo": "부근"},
    "仮に": {"meaning": "supposing", "meaningKo": "만약, 임시로"},
    "仰向け": {"meaning": "face up", "meaningKo": "위를 보고 누움"},
    "休暇明け": {"meaning": "post-vacation", "meaningKo": "휴가 끝남"},
    "休業": {"meaning": "closed", "meaningKo": "휴업"},
    "休養": {"meaning": "rest", "meaningKo": "휴양"},
    "伝染": {"meaning": "contagion", "meaningKo": "전염"},
    "低コスト": {"meaning": "low cost", "meaningKo": "저비용"},
    "低下": {"meaning": "fall", "meaningKo": "저하"},
    "低価格": {"meaning": "low price", "meaningKo": "저가격"},
    "低気圧": {"meaning": "low", "meaningKo": "저기압"},
    "住まい": {"meaning": "dwelling", "meaningKo": "주거, 집"},
    "住宅地": {"meaning": "housing district", "meaningKo": "주택지"},
    "体内": {"meaning": "interior of the body", "meaningKo": "체내"},
    "体制": {"meaning": "order", "meaningKo": "체제"},
    "体型": {"meaning": "figure", "meaningKo": "체형"},
    "体外": {"meaning": "ectogenesis", "meaningKo": "체외"},
    "体感": {"meaning": "bodily sensation", "meaningKo": "체감"},
    "体質": {"meaning": "constitution", "meaningKo": "체질"},
    "何らか": {"meaning": "some", "meaningKo": "어떠한, 약간의"},
    "何度も": {"meaning": "many times over", "meaningKo": "몇 번이나"},
    "作り上げる": {"meaning": "to build up", "meaningKo": "만들어 내다"},
    "作成": {"meaning": "drawing up", "meaningKo": "작성"},
    "使い分ける": {"meaning": "to use properly", "meaningKo": "구분해서 사용하다"},
    "例外": {"meaning": "exception", "meaningKo": "예외"},
    "価値観": {"meaning": "sense of values", "meaningKo": "가치관"},
    "係": {"meaning": "charge", "meaningKo": "담당자"},
    "保育園": {"meaning": "nursery school", "meaningKo": "어린이집"},
    "保育所": {"meaning": "nursery school", "meaningKo": "보육소"},
    "信頼性": {"meaning": "credibility", "meaningKo": "신뢰성"},
    "修学旅行": {"meaning": "excursion", "meaningKo": "수학여행"},
    "修業": {"meaning": "pursuit of knowledge", "meaningKo": "수업, 학업을 마침"},
    "個人差": {"meaning": "individual differences", "meaningKo": "개인차"},
    "個体": {"meaning": "individual", "meaningKo": "개체"},
    "倍増": {"meaning": "double", "meaningKo": "배증"},
    "値上がり": {"meaning": "price advance", "meaningKo": "가격 상승"},
    "偏る": {"meaning": "to lean", "meaningKo": "치우치다"},
    "偏食": {"meaning": "unbalanced diet", "meaningKo": "편식"},
    "停止": {"meaning": "stoppage", "meaningKo": "정지"},
    "催し": {"meaning": "event", "meaningKo": "행사, 모임"},
    "催促": {"meaning": "pressing", "meaningKo": "재촉"},
    "傷む": {"meaning": "to be spoiled", "meaningKo": "상하다"},
    "傷物": {"meaning": "defective article", "meaningKo": "흠집 난 물건"},
    "傾く": {"meaning": "to incline toward", "meaningKo": "기울다"},
    "傾らか": {"meaning": "gently sloping", "meaningKo": "완만함"},
    "働き手": {"meaning": "worker", "meaningKo": "일꾼"},
    "儀式": {"meaning": "ceremony", "meaningKo": "의식"},
    "優良": {"meaning": "superior", "meaningKo": "우량"},
    "充実感": {"meaning": "sense of fulfillment", "meaningKo": "충실감"},
    "充満": {"meaning": "being filled with", "meaningKo": "충만"},
    "充電": {"meaning": "charging", "meaningKo": "충전"},
    "先々": {"meaning": "distant future", "meaningKo": "장래, 가는 곳마다"},
    "先先週": {"meaning": "week before last", "meaningKo": "지지난 주"},
    "先端": {"meaning": "pointed end", "meaningKo": "첨단, 끝"},
    "光線": {"meaning": "beam", "meaningKo": "광선"},
    "児童": {"meaning": "children", "meaningKo": "아동"},
    "入り替える": {"meaning": "to replace", "meaningKo": "바꿔 넣다"},
    "入れ込む": {"meaning": "to put in", "meaningKo": "열중하다, 쏟아붓다"},
    "入会": {"meaning": "admission", "meaningKo": "입회"},
    "入会金": {"meaning": "initiation fee", "meaningKo": "입회비"},
    "入居": {"meaning": "moving into", "meaningKo": "입주"},
    "入居者": {"meaning": "tenant", "meaningKo": "입주자"},
    "入金": {"meaning": "deposit", "meaningKo": "입금"},
    "入門": {"meaning": "entering an institution", "meaningKo": "입문"},
    "全力": {"meaning": "all one’s power", "meaningKo": "전력"},
    "全面": {"meaning": "whole surface", "meaningKo": "전면"},
    "全面的": {"meaning": "total", "meaningKo": "전면적"},
    "全額": {"meaning": "total", "meaningKo": "전액"},
    "公害": {"meaning": "pollution", "meaningKo": "공해"},
    "公正": {"meaning": "justice", "meaningKo": "공정"},
    "公衆": {"meaning": "the public", "meaningKo": "공중"},
    "共有": {"meaning": "joint ownership", "meaningKo": "공유"},
    "内側": {"meaning": "inside", "meaningKo": "안쪽"},
    "内包": {"meaning": "connotation", "meaningKo": "내포"},
    "内線": {"meaning": "phone extension", "meaningKo": "내선"},
    "円形": {"meaning": "round shape", "meaningKo": "원형"},
    "再度": {"meaning": "twice", "meaningKo": "재차, 다시"},
    "再開": {"meaning": "reopening", "meaningKo": "재개"},
    "写生": {"meaning": "sketching", "meaningKo": "사생"},
    "写真家": {"meaning": "photographer", "meaningKo": "사진가"},
    "冷やす": {"meaning": "to cool", "meaningKo": "식히다"},
    "冷房": {"meaning": "cooling", "meaningKo": "냉방"},
    "冷水": {"meaning": "cold water", "meaningKo": "냉수"},
    "出席者": {"meaning": "those present", "meaningKo": "출석자"},
    "出来上がる": {"meaning": "to be completed", "meaningKo": "완성되다"},
    "出演者": {"meaning": "performer", "meaningKo": "출연자"},
    "出版社": {"meaning": "publisher", "meaningKo": "출판사"},
    "出発点": {"meaning": "starting point", "meaningKo": "출발점"},
    "出身地": {"meaning": "birthplace", "meaningKo": "출신지"},
    "分かれる": {"meaning": "to separate", "meaningKo": "나뉘다"},
    "分別": {"meaning": "separation", "meaningKo": "분별"},
    "分割": {"meaning": "partition", "meaningKo": "분할"},
    "分解": {"meaning": "disassembly", "meaningKo": "분해"},
    "分量": {"meaning": "amount", "meaningKo": "분량"},
    "切り上げる": {"meaning": "to close", "meaningKo": "마무리 짓다, 절상하다"},
    "切り取る": {"meaning": "to cut off", "meaningKo": "잘라내다"},
    "初回": {"meaning": "first time", "meaningKo": "초회, 첫 회"},
    "初夏": {"meaning": "early summer", "meaningKo": "초여름"},
    "初心者": {"meaning": "beginner", "meaningKo": "초보자"},
    "初期": {"meaning": "early", "meaningKo": "초기"},
    "別荘": {"meaning": "holiday house", "meaningKo": "별장"},
    "到底": {"meaning": "by no means", "meaningKo": "도저히"},
    "制作": {"meaning": "work", "meaningKo": "제작"},
    "刺す": {"meaning": "to pierce", "meaningKo": "찌르다"},
    "刻み込む": {"meaning": "to etch", "meaningKo": "새겨 넣다"},
    "刻む": {"meaning": "to mince", "meaningKo": "새기다, 잘게 썰다"},
    "削る": {"meaning": "to shave", "meaningKo": "깎다, 삭감하다"},
    "前半": {"meaning": "first half", "meaningKo": "전반"},
    "前向き": {"meaning": "front-facing", "meaningKo": "앞을 향함, 긍정적임"},
    "前回": {"meaning": "previous time", "meaningKo": "전회, 지난번"},
    "副": {"meaning": "assistant", "meaningKo": "부, 서브"},
    "創作": {"meaning": "creation", "meaningKo": "창작"},
    "劇的": {"meaning": "dramatic", "meaningKo": "극적"},
    "加熱": {"meaning": "heating", "meaningKo": "가열"},
    "加速": {"meaning": "acceleration", "meaningKo": "가속"},
    "助手席": {"meaning": "passenger seat", "meaningKo": "조수석"},
    "努める": {"meaning": "to endeavor", "meaningKo": "노력하다, 애쓰다"},
    "労働力": {"meaning": "labor", "meaningKo": "노동력"},
    "効力": {"meaning": "effect", "meaningKo": "효력"},
    "効用": {"meaning": "use", "meaningKo": "효용"},
    "動作": {"meaning": "action", "meaningKo": "동작"},
    "勘違い": {"meaning": "misunderstanding", "meaningKo": "착각"},
    "勝敗": {"meaning": "victory or defeat", "meaningKo": "승패"},
    "包丁": {"meaning": "kitchen knife", "meaningKo": "식칼"},
    "半数": {"meaning": "half the number", "meaningKo": "반수"},
    "半日": {"meaning": "half day", "meaningKo": "반나절"},
    "半減": {"meaning": "reduction by half", "meaningKo": "반감"},
    "半額": {"meaning": "half the amount", "meaningKo": "반액"},
    "卑怯": {"meaning": "cowardice", "meaningKo": "비겁함"},
    "単純明快": {"meaning": "simple and clear", "meaningKo": "단순 명쾌함"},
    "単身": {"meaning": "alone", "meaningKo": "단신, 홀몸"},
    "占う": {"meaning": "to tell someone’ fortune", "meaningKo": "점치다"},
    "印刷物": {"meaning": "printed matter", "meaningKo": "인쇄물"},
    "厚かましい": {"meaning": "impudent", "meaningKo": "뻔뻔스럽다"},
    "原料": {"meaning": "raw materials", "meaningKo": "원료"},
    "原理": {"meaning": "principle", "meaningKo": "원리"},
    "原産": {"meaning": "place of origin", "meaningKo": "원산"},
    "原稿": {"meaning": "manuscript", "meaningKo": "원고"},
    "厳守": {"meaning": "strict observance", "meaningKo": "엄수"},
    "参観": {"meaning": "visit", "meaningKo": "참관"},
    "反映": {"meaning": "reflection", "meaningKo": "반영"},
    "反論": {"meaning": "objection", "meaningKo": "반론"},
    "収納": {"meaning": "storage", "meaningKo": "수납"},
    "取り上げる": {"meaning": "to pick up", "meaningKo": "집어 들다, 채택하다"},
    "取り付く": {"meaning": "to cling to", "meaningKo": "매달리다, 착수하다"},
    "取り入れる": {"meaning": "to harvest", "meaningKo": "거두어들이다, 도입하다"},
    "取り掛かる": {"meaning": "to begin", "meaningKo": "착수하다"},
    "取り消し": {"meaning": "cancellation", "meaningKo": "취소"},
    "取り組み": {"meaning": "bout", "meaningKo": "씨름, 몰두함"},
    "取り込む": {"meaning": "to take in", "meaningKo": "거두어들이다, 혼잡하다"},
    "取得": {"meaning": "acquisition", "meaningKo": "취득"},
    "取扱": {"meaning": "treatment", "meaningKo": "취급"},
    "受け答え": {"meaning": "reply", "meaningKo": "응답, 대답"},
    "受動的": {"meaning": "passive", "meaningKo": "수동적"},
    "受診": {"meaning": "having a medical examination", "meaningKo": "진찰을 받음"},
    "受講": {"meaning": "taking", "meaningKo": "수강"},
    "受賞": {"meaning": "winning", "meaningKo": "수상"},
    "受験生": {"meaning": "student preparing for or taking examinations", "meaningKo": "수험생"},
    "口座": {"meaning": "account", "meaningKo": "계좌"},
    "古典": {"meaning": "classic", "meaningKo": "고전"},
    "古風": {"meaning": "old-fashioned", "meaningKo": "고풍"},
    "可愛がる": {"meaning": "to love", "meaningKo": "귀여워하다"},
    "司会": {"meaning": "leading a meeting", "meaningKo": "사회"},
    "各位": {"meaning": "everyone", "meaningKo": "각위, 여러분"},
    "各自": {"meaning": "each", "meaningKo": "각자"},
    "合同": {"meaning": "combination", "meaningKo": "합동"},
    "合宿": {"meaning": "lodging together", "meaningKo": "합숙"},
    "同年代": {"meaning": "the same generation", "meaningKo": "동년배"},
    "名づける": {"meaning": "to name", "meaningKo": "이름 짓다"},
    "名刺": {"meaning": "business card", "meaningKo": "명함"},
    "名所": {"meaning": "famous place", "meaningKo": "명소"},
    "名物": {"meaning": "famous product", "meaningKo": "명물"},
    "名門": {"meaning": "noted family", "meaningKo": "명문"},
    "向き合う": {"meaning": "to be opposite", "meaningKo": "마주 보다"},
    "含める": {"meaning": "to include", "meaningKo": "포함시키다, 타이르다"},
    "吸い取る": {"meaning": "to absorb", "meaningKo": "빨아들이다"},
    "呟く": {"meaning": "to mutter", "meaningKo": "중얼거리다"},
    "周年": {"meaning": "whole year", "meaningKo": "주년"},
    "周辺": {"meaning": "circumference", "meaningKo": "주변"},
    "味付け": {"meaning": "seasoning", "meaningKo": "양념, 간 맞추기"},
    "呼びかける": {"meaning": "to call out to", "meaningKo": "소리쳐 부르다, 호소하다"},
    "和食": {"meaning": "Japanese food", "meaningKo": "일식"},
    "商店街": {"meaning": "shopping district", "meaningKo": "상점가"},
    "商業": {"meaning": "commerce", "meaningKo": "상업"},
    "問いかける": {"meaning": "to ask a question", "meaningKo": "질문을 던지다"},
    "問い合わせ": {"meaning": "enquiry", "meaningKo": "문의"},
    "問題点": {"meaning": "the problem", "meaningKo": "문제점"},
    "喧しい": {"meaning": "noisy", "meaningKo": "시끄럽다, 까다롭다"},
    "嗅ぐ": {"meaning": "to sniff", "meaningKo": "냄새 맡다"},
    "器具": {"meaning": "utensil", "meaningKo": "기구"},
    "回答": {"meaning": "reply", "meaningKo": "해답, 답변"},
    "回転": {"meaning": "rotation", "meaningKo": "회전"},
    "図々しい": {"meaning": "impudent", "meaningKo": "뻔뻔스럽다"},
    "図表": {"meaning": "chart", "meaningKo": "도표"},
    "国々": {"meaning": "countries", "meaningKo": "나라들"},
    "圧勝": {"meaning": "complete victory", "meaningKo": "압승"},
    "在学": {"meaning": "attending", "meaningKo": "재학"},
    "在籍": {"meaning": "being enrolled", "meaningKo": "재적"},
    "地帯": {"meaning": "area", "meaningKo": "지대"},
    "地点": {"meaning": "site", "meaningKo": "지점"},
    "地球温暖化": {"meaning": "global warming", "meaningKo": "지구 온난화"},
    "坂道": {"meaning": "hill road", "meaningKo": "비탈길"},
    "垂直": {"meaning": "vertical", "meaningKo": "수직"},
    "塞ぐ": {"meaning": "to stop up", "meaningKo": "막다, 틀어막다"},
    "墓参り": {"meaning": "visit to a grave", "meaningKo": "성묘"},
    "増大": {"meaning": "enlargement", "meaningKo": "증대"},
    "増減": {"meaning": "increase and decrease", "meaningKo": "증감"},
    "売り上げ": {"meaning": "amount sold", "meaningKo": "매상, 매출액"},
    "売り切れ": {"meaning": "sold-out", "meaningKo": "매진"},
    "売れ行き": {"meaning": "sales", "meaningKo": "팔림새, 매상"},
    "変わった": {"meaning": "another", "meaningKo": "특이한, 색다른"},
    "変形": {"meaning": "transformation", "meaningKo": "변형"},
    "変換": {"meaning": "change", "meaningKo": "변환"},
    "夏期": {"meaning": "summer term", "meaningKo": "하계"},
    "夕日": {"meaning": "evening sun", "meaningKo": "석양"},
    "外側": {"meaning": "exterior", "meaningKo": "바깥쪽"},
    "外見": {"meaning": "outward appearance", "meaningKo": "외견, 겉보기"},
    "多く": {"meaning": "many", "meaningKo": "많음, 대다수"},
    "多大": {"meaning": "great", "meaningKo": "다대함, 막대함"},
    "多彩": {"meaning": "variegated", "meaningKo": "다채로움"},
    "多様化": {"meaning": "diversification", "meaningKo": "다양화"},
    "多様性": {"meaning": "diversity", "meaningKo": "다양성"},
    "多用": {"meaning": "busyness", "meaningKo": "다용, 바쁨"},
    "多発": {"meaning": "repeated occurrence", "meaningKo": "다발"},
    "多目に": {"meaning": "plenty", "meaningKo": "넉넉하게, 조금 많게"},
    "多種多様": {"meaning": "a great variety of", "meaningKo": "다종다양"},
    "多量": {"meaning": "large quantity", "meaningKo": "다량"},
    "多難": {"meaning": "full of troubles", "meaningKo": "다난, 어려움이 많음"},
    "多額": {"meaning": "large", "meaningKo": "다액, 거액"},
    "夜勤": {"meaning": "night shift", "meaningKo": "야근"},
    "夜型": {"meaning": "nocturnal", "meaningKo": "야행성"},
    "夜空": {"meaning": "night sky", "meaningKo": "밤하늘"},
    "夜遅く": {"meaning": "late at night", "meaningKo": "밤늦게"},
    "大人しい": {"meaning": "obedient", "meaningKo": "얌전하다, 온순하다"},
    "大別": {"meaning": "general classification", "meaningKo": "대별, 크게 나눔"},
    "大声": {"meaning": "loud voice", "meaningKo": "큰 소리"},
    "大学祭": {"meaning": "university festival", "meaningKo": "대학 축제"},
    "大学院": {"meaning": "graduate school", "meaningKo": "대학원"},
    "大手": {"meaning": "major company", "meaningKo": "대기업"},
    "大敵": {"meaning": "great rival", "meaningKo": "대적, 큰 적"},
    "大通り": {"meaning": "main street", "meaningKo": "큰길, 대로"},
    "天候不順": {"meaning": "unseasonable weather", "meaningKo": "불순한 날씨"},
    "奥底": {"meaning": "depths", "meaningKo": "깊은 속, 밑바닥"},
    "好印象": {"meaning": "good impression", "meaningKo": "호인상"},
    "好感": {"meaning": "good feeling", "meaningKo": "호감"},
    "妥当": {"meaning": "valid", "meaningKo": "타당함"},
    "妨げる": {"meaning": "to disturb", "meaningKo": "방해하다"},
    "娯楽": {"meaning": "pleasure", "meaningKo": "오락"},
    "嫌々": {"meaning": "unwillingly", "meaningKo": "마지못해, 싫은데 억지로"},
    "子育て": {"meaning": "child rearing", "meaningKo": "육아"},
    "存分": {"meaning": "to the fullest", "meaningKo": "마음껏, 충분히"},
    "学年": {"meaning": "academic year", "meaningKo": "학년"},
    "学業": {"meaning": "studies", "meaningKo": "학업"},
    "学生課": {"meaning": "student affairs office", "meaningKo": "학생과"},
    "学費": {"meaning": "tuition", "meaningKo": "학비"},
    "宅配": {"meaning": "home delivery", "meaningKo": "택배"},
    "宅配便": {"meaning": "express home delivery service", "meaningKo": "택배편"},
    "宇宙人": {"meaning": "space alien", "meaningKo": "우주인"},
    "安価": {"meaning": "low-priced", "meaningKo": "안가, 싼 값"},
    "安値": {"meaning": "low price", "meaningKo": "싼 값"},
    "安易": {"meaning": "easy", "meaningKo": "안이함"},
    "定価": {"meaning": "list price", "meaningKo": "정가"},
    "定員": {"meaning": "fixed number", "meaningKo": "정원"},
    "定着": {"meaning": "sticking", "meaningKo": "정착"},
    "宛": {"meaning": "addressed to", "meaningKo": "~앞, 수신인"},
    "実地": {"meaning": "practice", "meaningKo": "실지, 현장"},
    "実感": {"meaning": "real feeling", "meaningKo": "실감"},
    "実績": {"meaning": "achievements", "meaningKo": "실적"},
    "実用": {"meaning": "practical use", "meaningKo": "실용"},
    "実習": {"meaning": "practice", "meaningKo": "실습"},
    "実行": {"meaning": "execution", "meaningKo": "실행"},
    "実際": {"meaning": "practical", "meaningKo": "실제"},
    "実験": {"meaning": "experiment", "meaningKo": "실험"},
    "実験者": {"meaning": "experimenter", "meaningKo": "실험자"},
    "客席": {"meaning": "guest seating", "meaningKo": "객석"},
    "客観的": {"meaning": "objective", "meaningKo": "객관적"},
    "容量": {"meaning": "capacity", "meaningKo": "용량"},
    "宿泊先": {"meaning": "lodging place", "meaningKo": "숙박지"},
    "寄せる": {"meaning": "to come near", "meaningKo": "밀려오다, 바싹 대다"},
    "寄り道": {"meaning": "dropping in on the way", "meaningKo": "가는 길에 다른 데 들름"},
    "密着": {"meaning": "close adhesion", "meaningKo": "밀착"},
    "密閉": {"meaning": "shutting tightly", "meaningKo": "밀폐"},
    "寝転がる": {"meaning": "to lie down", "meaningKo": "아무렇게나 뒹굴다"},
    "寮": {"meaning": "hostel", "meaningKo": "기숙사"},
    "対": {"meaning": "opposite", "meaningKo": "대 (비율, 상대)"},
    "対戦": {"meaning": "waging war", "meaningKo": "대전, 겨룸"},
    "対立": {"meaning": "suitability", "meaningKo": "대립"},
    "対策": {"meaning": "measure", "meaningKo": "대책"},
    "対象外": {"meaning": "not covered", "meaningKo": "대상 외"},
    "寿命": {"meaning": "life span", "meaningKo": "수명"},
    "専属": {"meaning": "exclusive", "meaningKo": "전속"},
    "専念": {"meaning": "absorption", "meaningKo": "전념"},
    "専業主婦": {"meaning": "housewife", "meaningKo": "전업주부"},
    "専門店": {"meaning": "specialist shop", "meaningKo": "전문점"},
    "専門書": {"meaning": "technical book", "meaningKo": "전문서적"},
    "小物": {"meaning": "accessories", "meaningKo": "소품, 자잘한 물건"},
    "小遣い": {"meaning": "pocket money", "meaningKo": "용돈"},
    "小金": {"meaning": "small sum of money", "meaningKo": "적은 돈, 잔돈"},
    "少子化": {"meaning": "declining birth rates", "meaningKo": "저출산"},
    "就職活動": {"meaning": "job hunting", "meaningKo": "취직 활동, 구직 활동"},
    "居場所": {"meaning": "whereabouts", "meaningKo": "있을 곳"},
    "居心地": {"meaning": "comfort", "meaningKo": "머무는 기분"},
    "居酒屋": {"meaning": "izakaya", "meaningKo": "선술집, 이자카야"},
    "屋台": {"meaning": "cart", "meaningKo": "포장마차"},
    "屋外": {"meaning": "outdoors", "meaningKo": "옥외, 야외"},
    "属する": {"meaning": "to belong to", "meaningKo": "속하다"},
    "履歴書": {"meaning": "personal history", "meaningKo": "이력서"},
    "山頂": {"meaning": "summit", "meaningKo": "산정, 산꼭대기"},
    "崩す": {"meaning": "to destroy", "meaningKo": "무너뜨리다"},
    "巻き込む": {"meaning": "to roll up", "meaningKo": "말려들게 하다, 휩쓸리게 하다"},
    "市長": {"meaning": "mayor", "meaningKo": "시장"},
    "帰省": {"meaning": "homecoming", "meaningKo": "귀성"},
    "常温": {"meaning": "normal temperature", "meaningKo": "상온"},
    "幅広い": {"meaning": "extensive", "meaningKo": "폭넓다"},
    "平凡": {"meaning": "ordinary", "meaningKo": "평범함"},
    "平気": {"meaning": "coolness", "meaningKo": "아무렇지 않음, 태연함"},
    "年上": {"meaning": "older", "meaningKo": "연상"},
    "年内": {"meaning": "by the end of the year", "meaningKo": "연내"},
    "年取る": {"meaning": "to grow old", "meaningKo": "나이를 먹다"},
    "年度": {"meaning": "fiscal year", "meaningKo": "연도"},
    "年金": {"meaning": "annuity", "meaningKo": "연금"},
    "幻想": {"meaning": "fantasy", "meaningKo": "환상"},
    "幼稚": {"meaning": "infancy", "meaningKo": "유치함"},
    "幼稚園": {"meaning": "kindergarten", "meaningKo": "유치원"},
    "広々": {"meaning": "extensive", "meaningKo": "넓디넓은 모양"},
    "広がり": {"meaning": "spread", "meaningKo": "퍼짐, 넓어짐"},
    "広げる": {"meaning": "to spread", "meaningKo": "넓히다, 펼치다"},
    "広場": {"meaning": "plaza", "meaningKo": "광장"},
    "序列": {"meaning": "rank", "meaningKo": "서열"},
    "店長": {"meaning": "shop manager", "meaningKo": "점장"},
    "庭園": {"meaning": "garden", "meaningKo": "정원"},
    "延長": {"meaning": "extension", "meaningKo": "연장"},
    "弊社": {"meaning": "our firm", "meaningKo": "폐사 (자기를 낮추어 부르는 말)"},
    "引き取る": {"meaning": "to take into one’s care", "meaningKo": "떠맡다, 인수하다"},
    "引き止める": {"meaning": "to detain", "meaningKo": "만류하다, 말리다"},
    "引き渡す": {"meaning": "to deliver", "meaningKo": "인도하다, 넘겨주다"},
    "引き続き": {"meaning": "continuously", "meaningKo": "계속해서"},
    "引き込む": {"meaning": "to pull into", "meaningKo": "끌어들이다"},
    "引っかかる": {"meaning": "to be caught in", "meaningKo": "걸리다"},
    "弱々しい": {"meaning": "frail", "meaningKo": "가냘프다, 연약하다"},
    "弱気": {"meaning": "timid", "meaningKo": "약기, 기가 죽음"},
    "張り切る": {"meaning": "to be in high spirits", "meaningKo": "의욕이 넘치다, 벼르다"},
    "強み": {"meaning": "forte", "meaningKo": "강점"},
    "強化": {"meaning": "strengthening", "meaningKo": "강화"},
    "強引": {"meaning": "overbearing", "meaningKo": "억지로, 억지스러움"},
    "強弱": {"meaning": "strength and weakness", "meaningKo": "강약"},
    "強気": {"meaning": "confident", "meaningKo": "강기, 강경한 태도"},
    "強火": {"meaning": "high flame", "meaningKo": "강한 불"},
    "強風": {"meaning": "strong wind", "meaningKo": "강풍"},
    "当てはまる": {"meaning": "to apply", "meaningKo": "들어맞다, 적합하다"},
    "当分": {"meaning": "for the present", "meaningKo": "당분간"},
    "形式": {"meaning": "form", "meaningKo": "형식"},
    "彫刻": {"meaning": "carving", "meaningKo": "조각"},
    "彫刻家": {"meaning": "engraver", "meaningKo": "조각가"},
    "影響力": {"meaning": "influence", "meaningKo": "영향력"},
    "役目": {"meaning": "duty", "meaningKo": "역할, 임무"},
    "後半": {"meaning": "second half", "meaningKo": "후반"},
    "後戻り": {"meaning": "going backward", "meaningKo": "되돌아감, 뒷걸음질"},
    "後日": {"meaning": "in the future", "meaningKo": "후일, 훗날"},
    "後期": {"meaning": "latter period", "meaningKo": "후기"},
    "循環": {"meaning": "circulation", "meaningKo": "순환"},
    "心地良い": {"meaning": "comfortable", "meaningKo": "기분 좋다, 아늑하다"},
    "必着": {"meaning": "must arrive", "meaningKo": "필착 (반드시 도착해야 함)"},
    "必要不可欠": {"meaning": "essential", "meaningKo": "필요불가결"},
    "志願": {"meaning": "aspiration", "meaningKo": "지원"},
    "志願者": {"meaning": "applicant", "meaningKo": "지원자"},
    "忘れ去る": {"meaning": "to forget completely", "meaningKo": "완전히 잊어버리다"},
    "応える": {"meaning": "to respond", "meaningKo": "부응하다, 응답하다"},
    "応募者": {"meaning": "applicant", "meaningKo": "응모자"},
    "応答": {"meaning": "reply", "meaningKo": "응답"},
    "怖がる": {"meaning": "to be afraid of", "meaningKo": "무서워하다"},
    "思いがけない": {"meaning": "unexpected", "meaningKo": "뜻밖이다"},
    "思いつく": {"meaning": "to think of", "meaningKo": "생각해내다"},
    "思い切り": {"meaning": "to one's heart's content", "meaningKo": "마음껏, 결단력"},
    "思い浮かぶ": {"meaning": "to occur to", "meaningKo": "마음에 떠오르다"},
    "思い立つ": {"meaning": "to set one’s mind on doing", "meaningKo": "결심하다, 뜻을 세우다"},
    "思い込み": {"meaning": "wrong impression", "meaningKo": "단단히 믿어버림, 편견"},
    "思い返す": {"meaning": "to re-think", "meaningKo": "다시 생각하다, 마음을 고쳐먹다"},
    "思考力": {"meaning": "ability to think", "meaningKo": "사고력"},
    "急ぎ": {"meaning": "haste", "meaningKo": "급함, 서두름"},
    "急増": {"meaning": "rapid increase", "meaningKo": "급증"},
    "急病": {"meaning": "sudden illness", "meaningKo": "급병"},
    "性能": {"meaning": "ability", "meaningKo": "성능"},
    "性質": {"meaning": "nature", "meaningKo": "성질"},
    "恐縮": {"meaning": "feeling obliged", "meaningKo": "황송함"},
    "恒常": {"meaning": "constancy", "meaningKo": "항상, 일정함"},
    "恩恵": {"meaning": "grace", "meaningKo": "은혜"},
    "息抜き": {"meaning": "taking a breather", "meaningKo": "잠깐 쉼, 숨 돌리기"},
    "悔やむ": {"meaning": "to mourn", "meaningKo": "후회하다, 애도하다"},
    "悪影響": {"meaning": "bad influence", "meaningKo": "악영향"},
    "悪意": {"meaning": "ill will", "meaningKo": "악의"},
    "悪条件": {"meaning": "unfavorable conditions", "meaningKo": "악조건"},
    "情景": {"meaning": "spectacle", "meaningKo": "정경"},
    "惜しい": {"meaning": "regrettable", "meaningKo": "아깝다, 애석하다"},
    "惹く": {"meaning": "to draw", "meaningKo": "마음을 끌다"},
    "意地悪": {"meaning": "malicious", "meaningKo": "심술궂음"},
    "意外性": {"meaning": "unpredictability", "meaningKo": "의외성"},
    "意義": {"meaning": "meaning", "meaningKo": "의의"},
    "愛らしい": {"meaning": "pretty", "meaningKo": "사랑스럽다"},
    "愛用": {"meaning": "favorite", "meaningKo": "애용"},
    "愛着": {"meaning": "attachment", "meaningKo": "애착"},
    "愛社": {"meaning": "devotion to one’s company", "meaningKo": "애사 (회사를 사랑함)"},
    "感じ取る": {"meaning": "to perceive", "meaningKo": "감지하다, 알아차리다"},
    "慈善": {"meaning": "charity", "meaningKo": "자선"},
    "慌ただしい": {"meaning": "busy", "meaningKo": "어수선하다, 분주하다"},
    "成し遂げる": {"meaning": "to accomplish", "meaningKo": "이루어 내다"},
    "成分": {"meaning": "ingredient", "meaningKo": "성분"},
    "成立": {"meaning": "formation", "meaningKo": "성립"},
    "戦後": {"meaning": "postwar period", "meaningKo": "전후"},
    "戦略": {"meaning": "strategy", "meaningKo": "전략"},
    "所有": {"meaning": "possession", "meaningKo": "소유"},
    "手が空く": {"meaning": "to be free", "meaningKo": "일이 끝나 짬이 나다"},
    "手に付かない": {"meaning": "unable to concentrate on", "meaningKo": "손에 잡히지 않다 (집중이 안 되다)"},
    "手に入れる": {"meaning": "to obtain", "meaningKo": "손에 넣다"},
    "手作業": {"meaning": "manual labor", "meaningKo": "수작업"},
    "手入れ": {"meaning": "care", "meaningKo": "손질, 손보아 고침"},
    "手帳": {"meaning": "notebook", "meaningKo": "수첩"},
    "手数料": {"meaning": "handling charge", "meaningKo": "수수료"},
    "手早い": {"meaning": "nimble", "meaningKo": "재빠르다"},
    "手書き": {"meaning": "handwriting", "meaningKo": "손글씨"},
    "手続き": {"meaning": "procedure", "meaningKo": "수속, 절차"},
    "手足": {"meaning": "hands and feet", "meaningKo": "수족, 손발"},
    "手頃": {"meaning": "moderate", "meaningKo": "알맞음, 적당함"},
    "打ち合わせ": {"meaning": "advance arrangements", "meaningKo": "사전 협의"},
    "打ち明ける": {"meaning": "to confide", "meaningKo": "털어놓다, 숨김없이 이야기하다"},
    "折り畳む": {"meaning": "to fold up", "meaningKo": "접다"},
    "折り返し": {"meaning": "by return", "meaningKo": "곧장 되돌아감, 반환"},
    "抵抗感": {"meaning": "antipathy", "meaningKo": "저항감"},
    "押し付ける": {"meaning": "to press", "meaningKo": "밀어붙이다, 억지로 떠맡기다"},
    "抽象": {"meaning": "abstraction", "meaningKo": "추상"},
    "担当者": {"meaning": "person in charge", "meaningKo": "담당자"},
    "拘る": {"meaning": "to fuss over", "meaningKo": "구애되다, 얽매이다"},
    "拡充": {"meaning": "expansion", "meaningKo": "확충"},
    "持ち主": {"meaning": "owner", "meaningKo": "소유자, 주인"},
    "持ち出す": {"meaning": "to take out", "meaningKo": "꺼내다, 화제로 꺼내다"},
    "持ち込む": {"meaning": "to take something into", "meaningKo": "반입하다, 끌어들이다"},
    "持参": {"meaning": "bringing", "meaningKo": "지참"},
    "指標": {"meaning": "index", "meaningKo": "지표"},
    "挟む": {"meaning": "to hold between", "meaningKo": "사이에 끼우다"},
    "振り向く": {"meaning": "to turn one’s face", "meaningKo": "뒤돌아보다"},
    "振り込み": {"meaning": "payment made via bank deposit transfer", "meaningKo": "납입, 계좌 이체"},
    "探る": {"meaning": "to feel around for", "meaningKo": "더듬어 찾다, 탐색하다"},
    "接する": {"meaning": "to touch", "meaningKo": "접하다"},
    "接着": {"meaning": "adhesion", "meaningKo": "접착"},
    "接続": {"meaning": "connection", "meaningKo": "접속"},
    "推薦書": {"meaning": "recommendation", "meaningKo": "추천서"},
    "揃う": {"meaning": "to be complete", "meaningKo": "모이다, 갖추어지다"},
    "揃える": {"meaning": "to collect", "meaningKo": "모으다, 가지런히 하다"},
    "撮影": {"meaning": "photography", "meaningKo": "촬영"},
    "支援": {"meaning": "support", "meaningKo": "지원"},
    "改める": {"meaning": "to change", "meaningKo": "고치다, 변경하다"},
    "改正": {"meaning": "revision", "meaningKo": "개정"},
    "放映": {"meaning": "televising", "meaningKo": "방영"},
    "放課後": {"meaning": "after school", "meaningKo": "방과 후"},
    "政党": {"meaning": "political party", "meaningKo": "정당"},
    "敗れる": {"meaning": "to be defeated", "meaningKo": "패배하다, 지다"},
    "教わる": {"meaning": "to be taught", "meaningKo": "가르침을 받다"},
    "教養": {"meaning": "cultivation", "meaningKo": "교양"},
    "散らかす": {"meaning": "to scatter around", "meaningKo": "어질러 놓다"},
    "数々": {"meaning": "many", "meaningKo": "수많은"},
    "数値": {"meaning": "numerical value", "meaningKo": "수치"},
    "数分": {"meaning": "several minutes", "meaningKo": "수 분"},
    "数多く": {"meaning": "in great numbers", "meaningKo": "수많이"},
    "数量": {"meaning": "quantity", "meaningKo": "수량"},
    "整う": {"meaning": "to be ready", "meaningKo": "정돈되다, 갖추어지다"},
    "整備": {"meaning": "maintenance", "meaningKo": "정비"},
    "文献": {"meaning": "literature", "meaningKo": "문헌"},
    "文系": {"meaning": "humanities, social sciences, and fine arts", "meaningKo": "문과 계열"},
    "文面": {"meaning": "content of a letter", "meaningKo": "편지의 문면(내용)"},
    "新設": {"meaning": "establishing", "meaningKo": "신설"},
    "方針": {"meaning": "policy", "meaningKo": "방침"},
    "方面": {"meaning": "direction", "meaningKo": "방면"},
    "旅先": {"meaning": "destination", "meaningKo": "여행지"},
    "日差し": {"meaning": "sunlight", "meaningKo": "햇살"},
    "日帰り": {"meaning": "day trip", "meaningKo": "당일치기"},
    "日当たり": {"meaning": "exposure to the sun", "meaningKo": "햇볕이 드는 정도, 일조"},
    "日数": {"meaning": "a number of days", "meaningKo": "일수"},
    "日用品": {"meaning": "daily necessities", "meaningKo": "일용품"},
    "日課": {"meaning": "daily lesson", "meaningKo": "일과"},
    "日頃": {"meaning": "normally", "meaningKo": "평소, 늘"},
    "早まる": {"meaning": "to be brought forward", "meaningKo": "빨라지다, 앞당겨지다"},
    "早口": {"meaning": "fast-talking", "meaningKo": "말이 빠름"},
    "早速": {"meaning": "at once", "meaningKo": "조속, 즉시"},
    "明示": {"meaning": "elucidation", "meaningKo": "명시"},
    "昔話": {"meaning": "old tale", "meaningKo": "옛날이야기"},
    "映る": {"meaning": "to be reflected", "meaningKo": "비치다, 찍히다"},
    "時事": {"meaning": "events of the day", "meaningKo": "시사"},
    "時点": {"meaning": "point in time", "meaningKo": "시점"},
    "時給": {"meaning": "hourly pay", "meaningKo": "시급"},
    "時間帯": {"meaning": "period of time", "meaningKo": "시간대"},
    "普及": {"meaning": "diffusion", "meaningKo": "보급"},
    "暗闇": {"meaning": "darkness", "meaningKo": "어둠"},
    "暴れる": {"meaning": "to act violently", "meaningKo": "날뛰다, 난폭하게 굴다"},
    "曖昧": {"meaning": "vague", "meaningKo": "애매함"},
    "曲線": {"meaning": "curve", "meaningKo": "곡선"},
    "更新": {"meaning": "renewal", "meaningKo": "갱신"},
    "書店": {"meaning": "bookshop", "meaningKo": "서점"},
    "最低限": {"meaning": "minimum", "meaningKo": "최저한도"},
    "最大": {"meaning": "biggest", "meaningKo": "최대"},
    "最寄り": {"meaning": "nearest", "meaningKo": "가장 가까운 곳"},
    "最小限": {"meaning": "minimum", "meaningKo": "최소한도"},
    "最悪": {"meaning": "worst", "meaningKo": "최악"},
    "最新": {"meaning": "latest", "meaningKo": "최신"},
    "最終日": {"meaning": "last day", "meaningKo": "최종일, 마지막 날"},
    "最速": {"meaning": "fastest", "meaningKo": "가장 빠름"},
    "最適": {"meaning": "most suitable", "meaningKo": "최적"},
    "最高齢": {"meaning": "oldest", "meaningKo": "최고령"},
    "有人": {"meaning": "manned", "meaningKo": "유인 (사람이 있음)"},
    "有力者": {"meaning": "influential person", "meaningKo": "유력자"},
    "有害": {"meaning": "harmful", "meaningKo": "유해"},
    "有意義": {"meaning": "significant", "meaningKo": "유의미함, 뜻깊음"},
    "有無": {"meaning": "existence or nonexistence", "meaningKo": "유무"},
    "有給": {"meaning": "salaried", "meaningKo": "유급"},
    "有限": {"meaning": "finite", "meaningKo": "유한"},
    "木材": {"meaning": "lumber", "meaningKo": "목재"},
    "本心": {"meaning": "true feelings", "meaningKo": "본심"},
    "本日": {"meaning": "today", "meaningKo": "금일, 오늘"},
    "本来": {"meaning": "originally", "meaningKo": "본래"},
    "本業": {"meaning": "principal occupation", "meaningKo": "본업"},
    "本番": {"meaning": "performance", "meaningKo": "본번, 본무대 (연습이 아닌 실전)"},
    "本社": {"meaning": "head office", "meaningKo": "본사"},
    "材質": {"meaning": "material", "meaningKo": "재질"},
    "束ねる": {"meaning": "to tie up in a bundle", "meaningKo": "다발로 묶다"},
    "来場者": {"meaning": "those attending", "meaningKo": "입장자, 방문객"},
    "来学期": {"meaning": "next semester", "meaningKo": "다음 학기"},
    "来年度": {"meaning": "next year", "meaningKo": "내년도"},
    "来店": {"meaning": "coming to a store", "meaningKo": "내점 (가게에 옴)"},
    "来店者": {"meaning": "visitor", "meaningKo": "내점자"},
    "来日": {"meaning": "arrival in Japan", "meaningKo": "방일 (일본에 옴)"},
    "果実": {"meaning": "fruit", "meaningKo": "과실"},
    "枠組み": {"meaning": "frame", "meaningKo": "틀, 뼈대"},
    "染み付く": {"meaning": "to be indelibly stained or ingrained", "meaningKo": "물들다, 깊이 배다"},
    "校外": {"meaning": "out-of-school", "meaningKo": "교외"},
    "根っこ": {"meaning": "root", "meaningKo": "뿌리"},
    "根元/根本": {"meaning": "root", "meaningKo": "근원, 근본"},
    "根強い": {"meaning": "firmly rooted", "meaningKo": "뿌리 깊다"},
    "根性": {"meaning": "willpower", "meaningKo": "근성"},
    "格別": {"meaning": "particular", "meaningKo": "각별함"},
    "格好つける": {"meaning": "to affect a stylish air", "meaningKo": "멋부리다, 폼 잡다"},
    "格安": {"meaning": "cheap", "meaningKo": "저렴함"},
    "桁": {"meaning": "column", "meaningKo": "자릿수"},
    "案外": {"meaning": "unexpectedly", "meaningKo": "의외로, 뜻밖에"},
    "検索": {"meaning": "looking up", "meaningKo": "검색"},
    "検診": {"meaning": "physical examination", "meaningKo": "검진"},
    "概要": {"meaning": "outline", "meaningKo": "개요"},
    "構造": {"meaning": "structure", "meaningKo": "구조"},
    "機器": {"meaning": "device", "meaningKo": "기기"},
    "機敏": {"meaning": "clever", "meaningKo": "기민함"},
    "機種": {"meaning": "type of equipment", "meaningKo": "기종"},
    "欄": {"meaning": "section", "meaningKo": "란, 칸"},
    "欠かす": {"meaning": "to miss", "meaningKo": "빠뜨리다, 결여하다"},
    "欠かせない": {"meaning": "indispensable", "meaningKo": "빠뜨릴 수 없다, 필수적이다"},
    "次回": {"meaning": "next time", "meaningKo": "다음번, 차회"},
    "欧米": {"meaning": "Europe and America", "meaningKo": "구미 (유럽과 미국)"},
    "欲する": {"meaning": "to want", "meaningKo": "원하다, 바라다"},
    "欲張り": {"meaning": "greed", "meaningKo": "욕심쟁이"},
    "欲張る": {"meaning": "to covet", "meaningKo": "욕심부리다"},
    "欲求": {"meaning": "desire", "meaningKo": "욕구"},
    "歌詞": {"meaning": "song lyrics", "meaningKo": "가사"},
    "歓迎会": {"meaning": "welcome party", "meaningKo": "환영회"},
    "正門": {"meaning": "main gate", "meaningKo": "정문"},
    "正面": {"meaning": "front", "meaningKo": "정면"},
    "歩み寄る": {"meaning": "to compromise", "meaningKo": "다가가다, 타협하다"},
    "歩行": {"meaning": "walk", "meaningKo": "보행"},
    "残業代": {"meaning": "overtime pay", "meaningKo": "잔업수당"},
    "段取り": {"meaning": "programme", "meaningKo": "일의 순서, 절차"},
    "段階": {"meaning": "grade", "meaningKo": "단계"},
    "毛糸": {"meaning": "knitting wool", "meaningKo": "털실"},
    "氏名": {"meaning": "full name", "meaningKo": "성명"},
    "民家": {"meaning": "private house", "meaningKo": "민가"},
    "気が進まない": {"meaning": "reluctant to", "meaningKo": "마음이 내키지 않다"},
    "気が重い": {"meaning": "depressed", "meaningKo": "마음이 무겁다"},
    "気を使う": {"meaning": "to worry", "meaningKo": "신경을 쓰다"},
    "気を失う": {"meaning": "to lose consciousness", "meaningKo": "정신을 잃다"},
    "気を落とす": {"meaning": "to be discouraged", "meaningKo": "낙담하다"},
    "気分転換": {"meaning": "change of pace", "meaningKo": "기분 전환"},
    "気配": {"meaning": "indication", "meaningKo": "기척"},
    "気配り": {"meaning": "care", "meaningKo": "배려"},
    "水平": {"meaning": "horizontal", "meaningKo": "수평"},
    "水面": {"meaning": "water’s surface", "meaningKo": "수면"},
    "求人": {"meaning": "recruiting", "meaningKo": "구인"},
    "決め付ける": {"meaning": "to fix upon", "meaningKo": "단정짓다, 일방적으로 꾸짖다"},
    "決勝戦": {"meaning": "championship game", "meaningKo": "결승전"},
    "決着": {"meaning": "conclusion", "meaningKo": "결착, 끝이 남"},
    "油断": {"meaning": "negligence", "meaningKo": "방심"},
    "注意深い": {"meaning": "careful", "meaningKo": "주의 깊다"},
    "注意点": {"meaning": "important point", "meaningKo": "주의점"},
    "洗い出す": {"meaning": "to reveal something", "meaningKo": "철저히 조사하여 밝혀내다"},
    "洗剤": {"meaning": "detergent", "meaningKo": "세제"},
    "洗濯機": {"meaning": "washing machine", "meaningKo": "세탁기"},
    "洗練": {"meaning": "polish", "meaningKo": "세련"},
    "活力": {"meaning": "vitality", "meaningKo": "활력"},
    "活字": {"meaning": "printing type", "meaningKo": "활자"},
    "活躍": {"meaning": "activity", "meaningKo": "활약"},
    "浮かぶ": {"meaning": "to float", "meaningKo": "뜨다, 떠오르다"},
    "海水浴": {"meaning": "swimming in the ocean", "meaningKo": "해수욕"},
    "消化": {"meaning": "digestion", "meaningKo": "소화"},
    "消失": {"meaning": "dying out", "meaningKo": "소실"},
    "消極的": {"meaning": "negative", "meaningKo": "소극적"},
    "消耗": {"meaning": "exhaustion", "meaningKo": "소모"},
    "消費者": {"meaning": "consumer", "meaningKo": "소비자"},
    "深夜": {"meaning": "late at night", "meaningKo": "심야"},
    "添付": {"meaning": "attaching", "meaningKo": "첨부"},
    "清掃": {"meaning": "cleaning", "meaningKo": "청소"},
    "減速": {"meaning": "deceleration", "meaningKo": "감속"},
    "温厚": {"meaning": "gentle", "meaningKo": "온후함"},
    "測定": {"meaning": "measurement", "meaningKo": "측정"},
    "湧く": {"meaning": "to well", "meaningKo": "솟아나다"},
    "湿っぽい": {"meaning": "damp", "meaningKo": "습기차다, 우울하다"},
    "湿る": {"meaning": "to become damp", "meaningKo": "축축해지다"},
    "満員": {"meaning": "full house", "meaningKo": "만원"},
    "溜める": {"meaning": "to amass", "meaningKo": "모으다, 저축하다"},
    "溢れる": {"meaning": "to overflow", "meaningKo": "넘치다"},
    "溶かす": {"meaning": "to dissolve", "meaningKo": "녹이다"},
    "滝": {"meaning": "waterfall", "meaningKo": "폭포"},
    "潜む": {"meaning": "to lurk", "meaningKo": "숨다, 잠복하다"},
    "潜る": {"meaning": "to dive", "meaningKo": "잠수하다, 빠져나가다"},
    "潰す": {"meaning": "to smash", "meaningKo": "부수다, 망치다"},
    "濁る": {"meaning": "to become muddy", "meaningKo": "탁해지다, 흐려지다"},
    "濃厚": {"meaning": "rich", "meaningKo": "농후함"},
    "無意識": {"meaning": "unconsciousness", "meaningKo": "무의식"},
    "無数": {"meaning": "innumerable", "meaningKo": "무수함"},
    "無条件": {"meaning": "unconditional", "meaningKo": "무조건"},
    "無給": {"meaning": "unpaid", "meaningKo": "무급"},
    "無線": {"meaning": "radio", "meaningKo": "무선"},
    "無縁": {"meaning": "unrelated", "meaningKo": "무연, 연고가 없음"},
    "無関係": {"meaning": "unrelated", "meaningKo": "무관계"},
    "無関心": {"meaning": "apathetic", "meaningKo": "무관심"},
    "無限": {"meaning": "infinity", "meaningKo": "무한"},
    "焦げる": {"meaning": "to burn", "meaningKo": "눋다, 타다"},
    "焦り": {"meaning": "impatience", "meaningKo": "초조함"},
    "焦点": {"meaning": "focus", "meaningKo": "초점"},
    "熱する": {"meaning": "to heat up", "meaningKo": "가열하다"},
    "片付く": {"meaning": "to be put in order", "meaningKo": "정리되다, 처리되다"},
    "牧場": {"meaning": "farm", "meaningKo": "목장"},
    "物真似": {"meaning": "mimicry", "meaningKo": "성대모사, 흉내"},
    "特効薬": {"meaning": "specific medicine", "meaningKo": "특효약"},
    "特定": {"meaning": "specific", "meaningKo": "특정"},
    "特殊": {"meaning": "special", "meaningKo": "특수"},
    "特色": {"meaning": "characteristic", "meaningKo": "특색"},
    "狙う": {"meaning": "to aim at", "meaningKo": "겨누다, 노리다"},
    "独身者": {"meaning": "unmarried person", "meaningKo": "독신자"},
    "狭める": {"meaning": "to narrow", "meaningKo": "좁히다"},
    "猿真似": {"meaning": "indiscriminate imitation", "meaningKo": "원숭이 흉내, 맹목적 모방"},
    "率直": {"meaning": "frank", "meaningKo": "솔직함"},
    "現代人": {"meaning": "modern person", "meaningKo": "현대인"},
    "現在地": {"meaning": "present location", "meaningKo": "현재 위치"},
    "現時点": {"meaning": "present point", "meaningKo": "현시점"},
    "理系": {"meaning": "science", "meaningKo": "이과"},
    "甘やかす": {"meaning": "to pamper", "meaningKo": "응석받이로 키우다"},
    "生き残る": {"meaning": "to survive", "meaningKo": "살아남다"},
    "生き生き": {"meaning": "in a lively way", "meaningKo": "생생하게, 생기 있게"},
    "生中継": {"meaning": "live broadcast", "meaningKo": "생중계"},
    "生命力": {"meaning": "vitality", "meaningKo": "생명력"},
    "生得的": {"meaning": "innate", "meaningKo": "선천적"},
    "生産者": {"meaning": "manufacturer", "meaningKo": "생산자"},
    "用具": {"meaning": "tool", "meaningKo": "용구, 도구"},
    "用途": {"meaning": "use", "meaningKo": "용도"},
    "申請": {"meaning": "application", "meaningKo": "신청"},
    "申請書": {"meaning": "written application", "meaningKo": "신청서"},
    "町並み": {"meaning": "townscape", "meaningKo": "거리 풍경, 집들이 늘어선 모양"},
    "画用紙": {"meaning": "drawing paper", "meaningKo": "도화지"},
    "略す": {"meaning": "to abbreviate", "meaningKo": "생략하다"},
    "畳む": {"meaning": "to fold", "meaningKo": "접다"},
    "疑問点": {"meaning": "point of uncertainty", "meaningKo": "의문점"},
    "痛ましい": {"meaning": "pitiful", "meaningKo": "참혹하다, 안쓰럽다"},
    "痺れる": {"meaning": "to become numb", "meaningKo": "저리다, 마비되다"},
    "発想": {"meaning": "idea", "meaningKo": "발상"},
    "発揮": {"meaning": "show", "meaningKo": "발휘"},
    "発散": {"meaning": "emission", "meaningKo": "발산"},
    "発送": {"meaning": "sending", "meaningKo": "발송"},
    "登場": {"meaning": "entry", "meaningKo": "등장"},
    "登山家": {"meaning": "mountain climber", "meaningKo": "등산가"},
    "白衣": {"meaning": "white robe", "meaningKo": "백의, 흰 가운"},
    "的確": {"meaning": "precise", "meaningKo": "적확함, 정확함"},
    "皆無": {"meaning": "nonexistent", "meaningKo": "전무함"},
    "皿洗い": {"meaning": "washing-up", "meaningKo": "설거지"},
    "目印": {"meaning": "mark", "meaningKo": "안표, 표지"},
    "目当て": {"meaning": "mark", "meaningKo": "목적, 목표"},
    "目新しい": {"meaning": "original", "meaningKo": "새롭다, 진기하다"},
    "目的地": {"meaning": "place of destination", "meaningKo": "목적지"},
    "目立つ": {"meaning": "to be conspicuous", "meaningKo": "눈에 띄다"},

    # N2~N5 (이전 응답에 이어 추가 교정)
    "目線": {"meaning": "gaze, line of sight", "meaningKo": "시선"},
    "直立": {"meaning": "standing upright", "meaningKo": "직립, 똑바로 섬"},
    "相対的": {"meaning": "relative", "meaningKo": "상대적인"},
    "看護": {"meaning": "nursing", "meaningKo": "간호"},
    "真の": {"meaning": "true, genuine", "meaningKo": "진정한, 진짜의"},
    "矛盾": {"meaning": "contradiction", "meaningKo": "모순"},
    "研修会": {"meaning": "workshop, training seminar", "meaningKo": "연수회, 워크숍"},
    "礼儀作法": {"meaning": "etiquette, manners", "meaningKo": "예의범절"},
    "秀才": {"meaning": "prodigy, bright person", "meaningKo": "수재, 영재"},
    "空想": {"meaning": "daydream, fantasy", "meaningKo": "공상"},
    "立食": {"meaning": "stand-up meal", "meaningKo": "입식 (서서 먹음)"},
    "純粋": {"meaning": "pure, genuine", "meaningKo": "순수"},
    "素人": {"meaning": "amateur, novice", "meaningKo": "아마추어, 초보자"},
    "絞る": {"meaning": "to wring, to squeeze", "meaningKo": "짜다, 쥐어짜다"},
    "継続": {"meaning": "continuation", "meaningKo": "계속, 지속"},
    "繋がる": {"meaning": "to be connected, to be tied together", "meaningKo": "연결되다, 이어지다"},
    "美容院": {"meaning": "beauty parlor, hair salon", "meaningKo": "미용실"},
    "育児": {"meaning": "childcare", "meaningKo": "육아"},
    "能率": {"meaning": "efficiency", "meaningKo": "능률"},
    "脇道": {"meaning": "side road, digression", "meaningKo": "옆길, 샛길"},
    "腹を立てる": {"meaning": "to take offense, to get angry", "meaningKo": "화를 내다"},
    "膨大": {"meaning": "huge, vast", "meaningKo": "방대함, 엄청남"},
    "至急": {"meaning": "urgent, immediately", "meaningKo": "지급, 매우 급함"},
    "芯": {"meaning": "wick, core", "meaningKo": "심, 심지"},
    "芸能": {"meaning": "public entertainment, show business", "meaningKo": "예능"},
    "苦": {"meaning": "pain, suffering", "meaningKo": "고통, 괴로움"},
    "苦戦": {"meaning": "hard fight, struggle", "meaningKo": "고전"},
    "蒸発": {"meaning": "evaporation, disappearance", "meaningKo": "증발"},
    "薄暗い": {"meaning": "dim, gloomy", "meaningKo": "어둑한"},
    "蛍光灯": {"meaning": "fluorescent lamp", "meaningKo": "형광등"},
    "行列": {"meaning": "line, queue, procession", "meaningKo": "행렬, 줄"},
    "表紙": {"meaning": "cover (of a book)", "meaningKo": "표지, 겉장"},
    "要件": {"meaning": "important matter, requirement", "meaningKo": "요건, 중요한 조건"},
    "要旨": {"meaning": "point, summary", "meaningKo": "요지"},
    "見張る": {"meaning": "to stand watch, to keep an eye on", "meaningKo": "망보다, 감시하다"},
    "視点": {"meaning": "opinion, point of view", "meaningKo": "시점, 관점"},
    "観念": {"meaning": "idea, concept", "meaningKo": "관념"},
    "観戦": {"meaning": "watching a game", "meaningKo": "관전"},
    "解放": {"meaning": "release, liberation", "meaningKo": "해방"},
    "解散": {"meaning": "breaking up, dissolution", "meaningKo": "해산"},
    "触れ合い": {"meaning": "contact, emotional connection", "meaningKo": "서로 접촉함, 교감"},
    "計測": {"meaning": "measuring, measurement", "meaningKo": "계측, 측정"},
    "評論": {"meaning": "criticism, critique", "meaningKo": "평론"},
    "説教": {"meaning": "remonstration, preaching", "meaningKo": "설교"},
    "読み取る": {"meaning": "to read and understand, to grasp", "meaningKo": "알아차리다, 간파하다"},
    "課": {"meaning": "lesson, section, department", "meaningKo": "과 (부서, 교과)"},
    "諸": {"meaning": "various, many", "meaningKo": "여러, 모든"},
    "謙虚": {"meaning": "modest, humble", "meaningKo": "겸허, 겸손함"},
    "賞品": {"meaning": "prize", "meaningKo": "상품 (상으로 주는 물건)"},
    "車両": {"meaning": "rolling stock, vehicles", "meaningKo": "차량"},
    "辞退": {"meaning": "declining, refusal", "meaningKo": "사퇴, 사양"},
    "退出": {"meaning": "leaving, withdrawal", "meaningKo": "퇴출, 물러남"},
    "送付": {"meaning": "sending, forwarding", "meaningKo": "송부, 보냄"},
    "送信": {"meaning": "transmission, sending", "meaningKo": "송신, 전송"},
    "送客": {"meaning": "sending customers", "meaningKo": "송객, 손님을 보냄"},
    "速達": {"meaning": "express delivery", "meaningKo": "속달"},
    "進入": {"meaning": "entry, approach", "meaningKo": "진입"},
    "過度": {"meaning": "excessive", "meaningKo": "과도함"},
    "過程": {"meaning": "process", "meaningKo": "과정"},
    "道案内": {"meaning": "guidance, showing the way", "meaningKo": "길 안내"},
    "選出": {"meaning": "election, selection", "meaningKo": "선출"},
    "鍛える": {"meaning": "to forge, to train", "meaningKo": "단련하다"},
    "閉店": {"meaning": "closing up shop", "meaningKo": "폐점"},
    "開催": {"meaning": "holding an event", "meaningKo": "개최"},
    "開幕": {"meaning": "raising the curtain, opening", "meaningKo": "개막"},
    "非公式": {"meaning": "informal, unofficial", "meaningKo": "비공식"},
    "非凡": {"meaning": "extraordinary, uncommon", "meaningKo": "비범, 평범하지 않음"},
    "音量": {"meaning": "volume", "meaningKo": "음량"},
    "項目": {"meaning": "item, heading", "meaningKo": "항목"},
    "順位": {"meaning": "order, ranking", "meaningKo": "순위"},
    "順序": {"meaning": "order, sequence", "meaningKo": "순서"},
    "頼り": {"meaning": "reliance, dependence", "meaningKo": "의지, 의지할 곳"},
    "飛び散る": {"meaning": "to fly around, to scatter", "meaningKo": "사방으로 흩어지다"},
    "飼い主": {"meaning": "owner (of a pet)", "meaningKo": "사육주, 주인"},
    "駆け足": {"meaning": "running fast, double time", "meaningKo": "뛰어감, 구보"},
    "お産": {"meaning": "childbirth, delivery", "meaningKo": "출산"},
    "お負け": {"meaning": "freebie, extra", "meaningKo": "덤, 경품"},
    "ズバリ": {"meaning": "decisively, frankly", "meaningKo": "정곡을 찔러, 단도직입적으로"},
    "デモンストレーション": {"meaning": "demonstration, protest", "meaningKo": "데모, 시위"},
    "ばい菌": {"meaning": "germ, bacteria", "meaningKo": "세균, 바이러스"},
    "一度に": {"meaning": "all at once", "meaningKo": "한꺼번에"},
    "一応": {"meaning": "tentatively, just in case", "meaningKo": "일단, 우선"},
    "万一": {"meaning": "by some chance, in the unlikely event", "meaningKo": "만일, 만약"},
    "上司": {"meaning": "superior, boss", "meaningKo": "상사"},
    "上達": {"meaning": "improvement, progress", "meaningKo": "숙달, 향상"},
    "不用品": {"meaning": "disused article", "meaningKo": "불용품"},
    "主婦": {"meaning": "housewife", "meaningKo": "주부"},
    "主要": {"meaning": "chief, main", "meaningKo": "주요"},
    "事件": {"meaning": "incident, case", "meaningKo": "사건"},
    "交通費": {"meaning": "traveling expenses", "meaningKo": "교통비"},
    "人込み": {"meaning": "crowd of people", "meaningKo": "인파, 사람들로 붐빔"},
    "仕舞う": {"meaning": "to finish, to complete", "meaningKo": "끝내다, 마치다"},
    "付合い": {"meaning": "association, socializing", "meaningKo": "교제, 사귐"},
    "仲直り": {"meaning": "reconciliation", "meaningKo": "화해"},
    "会": {"meaning": "meeting, assembly", "meaningKo": "모임, 회"},
    "体力": {"meaning": "physical strength", "meaningKo": "체력"},
    "余裕": {"meaning": "surplus, margin, room", "meaningKo": "여유"},
    "保証": {"meaning": "guarantee, security", "meaningKo": "보증"},
    "借金": {"meaning": "debt, loan", "meaningKo": "빚, 차금"},
    "停車": {"meaning": "stopping (of a train/car)", "meaningKo": "정차"},
    "傾向": {"meaning": "tendency, trend", "meaningKo": "경향, 추세"},
    "元": {"meaning": "origin, root", "meaningKo": "원래, 근원"},
    "光景": {"meaning": "scene, spectacle", "meaningKo": "광경"},
    "党": {"meaning": "political party", "meaningKo": "당, 정당"},
    "入力": {"meaning": "input", "meaningKo": "입력"},
    "全体": {"meaning": "whole, entirety", "meaningKo": "전체"},
    "具体": {"meaning": "concrete, tangible", "meaningKo": "구체"},
    "刈る": {"meaning": "to cut, to mow", "meaningKo": "베다, 깎다"},
    "利口": {"meaning": "clever, intelligent", "meaningKo": "영리함, 똑똑함"},
    "刺激": {"meaning": "stimulus, impetus", "meaningKo": "자극"},
    "加減": {"meaning": "adjustment, condition", "meaningKo": "가감, 정도"},
    "勝手": {"meaning": "selfishness, convenience", "meaningKo": "제멋대로임, 형편"},
    "厄介": {"meaning": "trouble, burden", "meaningKo": "성가심, 귀찮음"},
    "友": {"meaning": "friend", "meaningKo": "벗, 친구"},
    "句": {"meaning": "phrase, clause", "meaningKo": "구절, 구"},
    "合図": {"meaning": "sign, signal", "meaningKo": "신호"},
    "含む": {"meaning": "to contain, to include", "meaningKo": "포함하다, 머금다"},
    "哲学": {"meaning": "philosophy", "meaningKo": "철학"},
    "唯": {"meaning": "only, merely", "meaningKo": "오직, 단지"},
    "善": {"meaning": "good, goodness", "meaningKo": "선, 착함"},
    "回": {"meaning": "counter for occurrences", "meaningKo": "회, 번 (횟수를 세는 단위)"},
    "土": {"meaning": "earth, soil", "meaningKo": "흙"},
    "型": {"meaning": "model, type, pattern", "meaningKo": "형, 틀, 타입"},
    "場": {"meaning": "place, setting", "meaningKo": "장, 장소"},
    "外食": {"meaning": "eating out", "meaningKo": "외식"},
    "大型": {"meaning": "large, large-sized", "meaningKo": "대형"},
    "大統領": {"meaning": "president", "meaningKo": "대통령"},
    "夫々": {"meaning": "each, respectively", "meaningKo": "각각"},
    "始まり": {"meaning": "beginning", "meaningKo": "시작"},
    "学": {"meaning": "learning, scholarship", "meaningKo": "학문, 배움"},
    "定期": {"meaning": "fixed period, regular", "meaningKo": "정기"},
    "実用": {"meaning": "practical use", "meaningKo": "실용"},
    "家事": {"meaning": "housework", "meaningKo": "가사, 집안일"},
    "対する": {"meaning": "to face, to be against", "meaningKo": "대하다, 마주하다"},
    "小包": {"meaning": "parcel, package", "meaningKo": "소포"},
    "屡々": {"meaning": "often, frequently", "meaningKo": "종종, 자주"},
    "帯": {"meaning": "sash, belt", "meaningKo": "띠"},
    "平ら": {"meaning": "flat, level", "meaningKo": "평평함"},
    "底": {"meaning": "bottom, sole", "meaningKo": "바닥, 밑"},
    "強盗": {"meaning": "robber, burglary", "meaningKo": "강도"},
    "従う": {"meaning": "to follow, to obey", "meaningKo": "따르다, 순종하다"},
    "性": {"meaning": "gender, nature", "meaningKo": "성, 성별, 성질"},
    "恐怖": {"meaning": "fear, terror", "meaningKo": "공포"},
    "悪口": {"meaning": "bad mouth, insult", "meaningKo": "욕, 험담"},
    "意識": {"meaning": "consciousness, awareness", "meaningKo": "의식"},
    "我々": {"meaning": "we", "meaningKo": "우리들"},
    "手段": {"meaning": "means, method", "meaningKo": "수단, 방법"},
    "技師": {"meaning": "engineer, technician", "meaningKo": "기사, 기술자"},
    "指す": {"meaning": "to point, to indicate", "meaningKo": "가리키다, 지목하다"},
    "掴む": {"meaning": "to seize, to catch", "meaningKo": "쥐다, 잡다"},
    "撫でる": {"meaning": "to stroke, to caress", "meaningKo": "쓰다듬다, 어루만지다"},
    "放題": {"meaning": "as one pleases", "meaningKo": "마음껏 ~함 (예: 食べ放題)"},
    "敬意": {"meaning": "respect, honor", "meaningKo": "경의"},
    "新た": {"meaning": "new, fresh", "meaningKo": "새로움"},
    "明かり": {"meaning": "light, illumination", "meaningKo": "불빛, 밝기"},
    "昼食": {"meaning": "lunch", "meaningKo": "중식, 점심"},
    "書斎": {"meaning": "study room", "meaningKo": "서재"},
    "有らゆる": {"meaning": "all, every", "meaningKo": "온갖, 모든"},
    "末": {"meaning": "end, tip", "meaningKo": "끝, 말"},
    "札": {"meaning": "tag, paper money", "meaningKo": "지폐, 꼬리표"},
    "株": {"meaning": "stock, share, stump", "meaningKo": "주식, (식물의) 포기"},
    "楽": {"meaning": "comfort, ease", "meaningKo": "편안함, 안락"},
    "機関": {"meaning": "engine, institution", "meaningKo": "기관"},
    "正": {"meaning": "true, regular, positive", "meaningKo": "정 (양수, 바름)"},
    "段": {"meaning": "steps, stair, level", "meaningKo": "단, 계단"},
    "毒": {"meaning": "poison", "meaningKo": "독"},
    "気味": {"meaning": "sensation, tendency", "meaningKo": "기미, 기분, 경향"},
    "決まり": {"meaning": "rule, settlement", "meaningKo": "규칙, 결정"},
    "注文": {"meaning": "order, request", "meaningKo": "주문"},
    "消費": {"meaning": "consumption", "meaningKo": "소비"},
    "渋滞": {"meaning": "traffic jam, congestion", "meaningKo": "정체, 밀림"},
    "湿度": {"meaning": "humidity", "meaningKo": "습도"},
    "演技": {"meaning": "acting, performance", "meaningKo": "연기"},
    "然も": {"meaning": "moreover, furthermore", "meaningKo": "게다가, 그 위에"},
    "物質": {"meaning": "material, substance", "meaningKo": "물질"},
    "状況": {"meaning": "state of affairs, situation", "meaningKo": "상황"},
    "現金": {"meaning": "cash", "meaningKo": "현금"},
    "男女": {"meaning": "men and women", "meaningKo": "남녀"},
    "略": {"meaning": "abbreviation, omission", "meaningKo": "생략, 약어"},
    "癖": {"meaning": "habit, peculiarity", "meaningKo": "버릇"},
    "盛り": {"meaning": "serving, helping, peak", "meaningKo": "담음, 분량, 한창때"},
    "省く": {"meaning": "to omit, to save", "meaningKo": "생략하다, 덜다"},
    "真逆": {"meaning": "exact opposite", "meaningKo": "정반대"},
    "知能": {"meaning": "intelligence", "meaningKo": "지능"},
    "硬貨": {"meaning": "coin", "meaningKo": "동전"},
    "神経": {"meaning": "nerve, sensitivity", "meaningKo": "신경"},
    "種": {"meaning": "seed, cause", "meaningKo": "씨앗, 원인"},
    "穴": {"meaning": "hole", "meaningKo": "구멍"},
    "章": {"meaning": "chapter, section", "meaningKo": "장 (글의 단락)"},
    "籠": {"meaning": "basket, cage", "meaningKo": "바구니, 새장"},
    "級": {"meaning": "class, grade", "meaningKo": "급, 등급"},
    "結果": {"meaning": "result, consequence", "meaningKo": "결과"},
    "縦": {"meaning": "vertical, length", "meaningKo": "세로"},
    "羽": {"meaning": "feather, wing", "meaningKo": "깃털, 날개"},
    "考え": {"meaning": "thinking, idea", "meaningKo": "생각, 아이디어"},
    "能": {"meaning": "talent, ability", "meaningKo": "능력, 재능"},
    "自身": {"meaning": "oneself", "meaningKo": "자신"},
    "芝居": {"meaning": "play, drama", "meaningKo": "연극"},
    "苦手": {"meaning": "poor at, weak in", "meaningKo": "서투름, 취약함"},
    "行動": {"meaning": "action, behavior", "meaningKo": "행동"},
    "裸": {"meaning": "naked, nude", "meaningKo": "알몸, 벌거숭이"},
    "要求": {"meaning": "demand, request", "meaningKo": "요구"},
    "見送り": {"meaning": "seeing someone off", "meaningKo": "배웅"},
    "解く": {"meaning": "to untie, to solve", "meaningKo": "풀다"},
    "記入": {"meaning": "entry, filling in", "meaningKo": "기입"},
    "訪問": {"meaning": "visit", "meaningKo": "방문"},
    "試し": {"meaning": "trial, test", "meaningKo": "시험, 시도"},
    "語学": {"meaning": "language study", "meaningKo": "어학"},
    "説": {"meaning": "theory, view", "meaningKo": "설, 학설"},
    "議員": {"meaning": "member of an assembly", "meaningKo": "의원"},
    "負け": {"meaning": "defeat, loss", "meaningKo": "패배, 짐"},
    "販売": {"meaning": "sales, selling", "meaningKo": "판매"},
    "質": {"meaning": "quality", "meaningKo": "질, 품질"},
    "跡": {"meaning": "trace, tracks", "meaningKo": "자취, 흔적"},
    "軍": {"meaning": "army, military", "meaningKo": "군, 군대"},
    "迎え": {"meaning": "meeting, greeting", "meaningKo": "마중"},
    "退屈": {"meaning": "tedium, boredom", "meaningKo": "지루함, 따분함"},
    "通知": {"meaning": "notice, notification", "meaningKo": "통지"},
    "連想": {"meaning": "association of ideas", "meaningKo": "연상"},
    "道徳": {"meaning": "morals, morality", "meaningKo": "도덕"},
    "適する": {"meaning": "to fit, to suit", "meaningKo": "적합하다, 알맞다"},
    "都": {"meaning": "capital, metropolis", "meaningKo": "도읍, 수도"},
    "野": {"meaning": "field, plain", "meaningKo": "들, 들판"},
    "釣": {"meaning": "fishing, change", "meaningKo": "낚시, 거스름돈"},
    "鋭い": {"meaning": "sharp, pointed", "meaningKo": "날카로운"},
    "間違い": {"meaning": "mistake, error", "meaningKo": "틀림, 실수"},
    "限界": {"meaning": "limit, bound", "meaningKo": "한계"},
    "雰囲気": {"meaning": "atmosphere, mood", "meaningKo": "분위기"},
    "面": {"meaning": "face, surface", "meaningKo": "면, 얼굴, 표면"},
    "順": {"meaning": "order, turn", "meaningKo": "순서, 차례"},
    "風景": {"meaning": "scenery, landscape", "meaningKo": "풍경"},
    "飯": {"meaning": "cooked rice, meal", "meaningKo": "밥, 식사"},
    "餌": {"meaning": "feed, bait", "meaningKo": "먹이, 미끼"},
    "鬼": {"meaning": "demon, ogre", "meaningKo": "귀신, 도깨비"},
    "アンコール": {"meaning": "encore", "meaningKo": "앙코르, 재청"},
    "ずれ": {"meaning": "gap, lag", "meaningKo": "어긋남, 차이"},
    "バー": {"meaning": "bar", "meaningKo": "바, 술집"},
    "パンク": {"meaning": "puncture, flat tire", "meaningKo": "펑크"},
    "フロント": {"meaning": "front, reception", "meaningKo": "프런트, 앞, 접수처"},
    "ポイント": {"meaning": "point, key part", "meaningKo": "포인트, 요점"},
    "メーカー": {"meaning": "manufacturer, maker", "meaningKo": "제조사, 메이커"},
    "レンジ": {"meaning": "microwave oven, range", "meaningKo": "레인지 (전자레인지 등)"},
    "丁寧": {"meaning": "polite, careful", "meaningKo": "정중함, 꼼꼼함"},
    "中々": {"meaning": "very, considerably", "meaningKo": "꽤, 좀처럼"},
    "事": {"meaning": "thing, matter", "meaningKo": "일, 것"},
    "以上": {"meaning": "more than, beyond", "meaningKo": "이상"},
    "倍": {"meaning": "double, times", "meaningKo": "배, 곱절"},
    "先輩": {"meaning": "senior", "meaningKo": "선배"},
    "別": {"meaning": "distinction, different", "meaningKo": "다름, 구별, 별도"},
    "包む": {"meaning": "to wrap up", "meaningKo": "싸다, 포장하다"},
    "受付": {"meaning": "reception desk", "meaningKo": "접수처, 접수"},
    "品物": {"meaning": "goods, article", "meaningKo": "물품, 물건"},
    "売り場": {"meaning": "sales floor, counter", "meaningKo": "매장, 파는 곳"},
    "大事": {"meaning": "important, serious", "meaningKo": "중요함, 큰일"},
    "尋ねる": {"meaning": "to ask, to inquire", "meaningKo": "묻다, 질문하다"},
    "布団": {"meaning": "futon, bedding", "meaningKo": "이불"},
    "形": {"meaning": "form, shape", "meaningKo": "모양, 형태"},
    "急": {"meaning": "sudden, urgent", "meaningKo": "급함, 갑작스러움"},
    "意見": {"meaning": "opinion", "meaningKo": "의견"},
    "支度": {"meaning": "preparation", "meaningKo": "채비, 준비"},
    "旨い": {"meaning": "delicious, skillful", "meaningKo": "맛있다, 솜씨가 좋다"},
    "格好": {"meaning": "shape, appearance", "meaningKo": "모습, 모양, 체면"},
    "気": {"meaning": "spirit, mood", "meaningKo": "기분, 마음, 기운"},
    "泥棒": {"meaning": "thief, burglar", "meaningKo": "도둑"},
    "点": {"meaning": "point, dot", "meaningKo": "점, 점수"},
    "用": {"meaning": "business, task", "meaningKo": "볼일, 용무"},
    "番組": {"meaning": "program", "meaningKo": "방송 프로그램"},
    "石": {"meaning": "stone", "meaningKo": "돌"},
    "糸": {"meaning": "thread, yarn", "meaningKo": "실"},
    "考える": {"meaning": "to think", "meaningKo": "생각하다"},
    "草": {"meaning": "grass, weed", "meaningKo": "풀"},
    "表": {"meaning": "table, chart", "meaningKo": "표 (도표)"},
    "訳": {"meaning": "translation, reason", "meaningKo": "번역, 까닭, 이유"},
    "講堂": {"meaning": "auditorium, lecture hall", "meaningKo": "강당"},
    "起こす": {"meaning": "to wake someone, to cause", "meaningKo": "일으키다, 깨우다"},
    "角": {"meaning": "corner", "meaningKo": "모퉁이, 구석"},
    "話す": {"meaning": "to speak, to talk", "meaningKo": "말하다, 이야기하다"},
    "貼る": {"meaning": "to stick, to paste", "meaningKo": "붙이다"},
    "駄目": {"meaning": "no good, useless", "meaningKo": "안 됨, 소용없음"},
    "ガイド": {"meaning": "guide", "meaningKo": "가이드, 안내"},
    "コーナー": {"meaning": "corner", "meaningKo": "코너, 모퉁이"},
    "コンパス": {"meaning": "compass", "meaningKo": "컴퍼스, 나침반"},
    "ペコペコ": {"meaning": "very hungry, fawning", "meaningKo": "배가 몹시 고픔, 굽실거림"},
    "テープレコーダー": {"meaning": "tape recorder", "meaningKo": "테이프 레코더"},
    "なる": {"meaning": "to become", "meaningKo": "되다"},
    "上": {"meaning": "up, above", "meaningKo": "위, 위쪽"},
    "下": {"meaning": "down, below", "meaningKo": "아래, 아래쪽"},
    "不味い": {"meaning": "unappetizing, unskillful", "meaningKo": "맛없다, 서투르다"},
    "何": {"meaning": "what", "meaningKo": "무엇"},
    "字": {"meaning": "character, letter", "meaningKo": "글자, 글씨"},
    "席": {"meaning": "seat", "meaningKo": "자리, 좌석"},
    "少し": {"meaning": "a little, some", "meaningKo": "조금, 약간"},
    "方": {"meaning": "direction, side", "meaningKo": "방향, 쪽"},
    "有る": {"meaning": "to be, to exist", "meaningKo": "있다"},
    "目": {"meaning": "eye", "meaningKo": "눈"},
    "酒": {"meaning": "alcohol, sake", "meaningKo": "술"}
}

# 2. 잘못 지정된 품사(Parts) 일괄 교정 사전
MANUAL_POS_FIXES = {
    "枠": "noun",
    "悪": "noun",
    "党": "noun",
    "毒": "noun",
    "丸々": "adverb",
    "見晴らし": "noun",
    "下等": "noun",
    "佳句": "noun",
    "対して": "particle",
    "あの": "adjective"
}